"""Static configuration"""

from typing import Mapping

from homeassistant.components.tts import Voice

VALID_LANGUAGES: Mapping[str, list[str]] = {
    "volc.bigasr.sauc.duration": ["zh-CN", "en-US", "ja-JP", "id-ID", "es-MX", "pt-BR", "de-DE", "fr-FR", "ko-KR", "fil-PH", "ms-MY", "th-TH", "ar-SA", "it-IT", "bn-BD", "el-GR", "nl-NL", "ru-RU", "tr-TR", "vi-VN", "pl-PL", "ro-RO", "ne-NP", "uk-UA", "yue-CN"],
    "volc.bigasr.sauc.concurrent": ["zh-CN", "en-US", "ja-JP", "id-ID", "es-MX", "pt-BR", "de-DE", "fr-FR", "ko-KR", "fil-PH", "ms-MY", "th-TH", "ar-SA", "it-IT", "bn-BD", "el-GR", "nl-NL", "ru-RU", "tr-TR", "vi-VN", "pl-PL", "ro-RO", "ne-NP", "uk-UA", "yue-CN"],
    "volc.seedasr.sauc.duration": ["zh-CN", "en-US", "ja-JP", "id-ID", "es-MX", "pt-BR", "de-DE", "fr-FR", "ko-KR", "fil-PH", "ms-MY", "th-TH", "ar-SA", "it-IT", "bn-BD", "el-GR", "nl-NL", "ru-RU", "tr-TR", "vi-VN", "pl-PL", "ro-RO", "ne-NP", "uk-UA", "yue-CN"],
    "volc.seedasr.sauc.concurrent": ["zh-CN", "en-US", "ja-JP", "id-ID", "es-MX", "pt-BR", "de-DE", "fr-FR", "ko-KR", "fil-PH", "ms-MY", "th-TH", "ar-SA", "it-IT", "bn-BD", "el-GR", "nl-NL", "ru-RU", "tr-TR", "vi-VN", "pl-PL", "ro-RO", "ne-NP", "uk-UA", "yue-CN"]
}

DEFAULT_VOICES: Mapping[str, str] = {
    "seed-tts-2.0": "zh_female_vv_uranus_bigtts",
    "seed-tts-1.0": "zh_female_vv_mars_bigtts",
    "seed-tts-1.0-concurr": "zh_female_vv_mars_bigtts"
}

# VALID_VOICES_START
VALID_VOICES: Mapping[str, Mapping[str, list[Voice]]] = {
    "seed-tts-2.0": {
        "zh-CN": [
            Voice(voice_id="ICL_uranus_zh_female_aojiaonvyou_tob", name="傲娇女友2.0"),
            Voice(voice_id="ICL_uranus_zh_female_aomanjiaosheng_tob", name="傲慢娇声2.0"),
            Voice(voice_id="ICL_uranus_zh_female_bingjiaojiejie_tob", name="病娇姐姐2.0"),
            Voice(voice_id="ICL_uranus_zh_female_bingjiaomengmei_tob", name="病娇萌妹2.0"),
            Voice(voice_id="ICL_uranus_zh_female_bingruoshaonv_tob", name="病弱少女2.0"),
            Voice(voice_id="ICL_uranus_zh_female_chengshujiejie_tob", name="成熟姐姐2.0"),
            Voice(voice_id="ICL_uranus_zh_female_chengshuwenrou_tob", name="成熟温柔2.0"),
            Voice(voice_id="ICL_uranus_zh_female_chuliannvyou_tob", name="初恋女友2.0"),
            Voice(voice_id="ICL_uranus_zh_female_chunchenvsheng_tob", name="纯澈女生2.0"),
            Voice(voice_id="ICL_uranus_zh_female_chunzhenshaonv_tob", name="纯真少女2.0"),
            Voice(voice_id="ICL_uranus_zh_female_guaiqiaokeer_tob", name="乖巧可儿2.0"),
            Voice(voice_id="ICL_uranus_zh_female_heainainai_tob", name="和蔼奶奶2.0"),
            Voice(voice_id="ICL_uranus_zh_female_huopodiaoman_tob", name="活泼刁蛮2.0"),
            Voice(voice_id="ICL_uranus_zh_female_huoponvhai_tob", name="活泼女孩2.0"),
            Voice(voice_id="ICL_uranus_zh_female_jiaohannvwang_tob", name="娇憨女王2.0"),
            Voice(voice_id="ICL_uranus_zh_female_jiaoruoluoli_tob", name="娇弱萝莉2.0"),
            Voice(voice_id="ICL_uranus_zh_female_jiaxiaozi_tob", name="假小子2.0"),
            Voice(voice_id="ICL_uranus_zh_female_jinglingxiangdao_tob",
                  name="精灵向导2.0"),
            Voice(voice_id="ICL_uranus_zh_female_kailangtingting_tob", name="开朗婷婷2.0"),
            Voice(voice_id="ICL_uranus_zh_female_kaixinxiaohong_tob", name="开心小鸿2.0"),
            Voice(voice_id="ICL_uranus_zh_female_keainvsheng_tob", name="可爱女生2.0"),
            Voice(voice_id="ICL_uranus_zh_female_lingdongxinxin_tob", name="灵动欣欣2.0"),
            Voice(voice_id="ICL_uranus_zh_female_linjuayi_tob", name="邻居阿姨2.0"),
            Voice(voice_id="ICL_uranus_zh_female_lixingyuanzi_tob", name="理性圆子2.0"),
            Voice(voice_id="ICL_uranus_zh_female_nuanxinqianqian_tob", name="暖心茜茜2.0"),
            Voice(voice_id="ICL_uranus_zh_female_nuanxinxuejie_tob", name="暖心学姐2.0"),
            Voice(voice_id="ICL_uranus_zh_female_qinglenggaoya_tob", name="清冷高雅2.0"),
            Voice(voice_id="ICL_uranus_zh_female_qingtianmeimei_tob", name="清甜莓莓2.0"),
            Voice(voice_id="ICL_uranus_zh_female_qingtiantaotao_tob", name="清甜桃桃2.0"),
            Voice(voice_id="ICL_uranus_zh_female_qingxinshaonv_tob", name="倾心少女2.0"),
            Voice(voice_id="ICL_uranus_zh_female_qingxixiaoxue_tob", name="清晰小雪2.0"),
            Voice(voice_id="ICL_uranus_zh_female_qingyingduoduo_tob", name="轻盈朵朵2.0"),
            Voice(voice_id="ICL_uranus_zh_female_reqingaina_tob", name="热情艾娜2.0"),
            Voice(voice_id="ICL_uranus_zh_female_rouguhunshi_tob", name="柔骨魂师2.0"),
            Voice(voice_id="ICL_uranus_zh_female_ruanmengtangtang_tob",
                  name="软萌糖糖2.0"),
            Voice(voice_id="ICL_uranus_zh_female_ruanmengtuanzi_tob", name="软萌团子2.0"),
            Voice(voice_id="ICL_uranus_zh_female_tianmeihuopo_tob", name="甜美活泼2.0"),
            Voice(voice_id="ICL_uranus_zh_female_tianmeijiaoqiao_tob", name="甜美娇俏2.0"),
            Voice(voice_id="ICL_uranus_zh_female_tianmeixiaoju_tob", name="甜美小橘2.0"),
            Voice(voice_id="ICL_uranus_zh_female_tianmeixiaoyu_tob", name="甜美小雨2.0"),
            Voice(voice_id="ICL_uranus_zh_female_tiaopigongzhu_tob", name="调皮公主2.0"),
            Voice(voice_id="ICL_uranus_zh_female_tiexinguimi_tob", name="贴心闺蜜2.0"),
            Voice(voice_id="ICL_uranus_zh_female_tiexinmeimei_tob", name="贴心妹妹2.0"),
            Voice(voice_id="ICL_uranus_zh_female_tiexinnvyou_tob", name="贴心女友2.0"),
            Voice(voice_id="ICL_uranus_zh_female_wenroubaiyueguang_tob",
                  name="温柔白月光2.0"),
            Voice(voice_id="ICL_uranus_zh_female_wenrounvshen_tob", name="温柔女神2.0"),
            Voice(voice_id="ICL_uranus_zh_female_wenrouwenya_tob", name="温柔文雅2.0"),
            Voice(voice_id="ICL_uranus_zh_female_wenwanshanshan_tob", name="温婉珊珊2.0"),
            Voice(voice_id="ICL_uranus_zh_female_wumeikeren_tob", name="妩媚可人2.0"),
            Voice(voice_id="ICL_uranus_zh_female_wumeiyujie_tob", name="妩媚御姐2.0"),
            Voice(voice_id="ICL_uranus_zh_female_xiemeinvwang_tob", name="邪魅女王2.0"),
            Voice(voice_id="ICL_uranus_zh_female_xiemeiyujie_tob", name="邪魅御姐2.0"),
            Voice(voice_id="ICL_uranus_zh_female_xingganmeihuo_tob", name="性感魅惑2.0"),
            Voice(voice_id="ICL_uranus_zh_female_xingganyujie_tob", name="性感御姐2.0"),
            Voice(voice_id="ICL_uranus_zh_female_xiuliqianqian_tob", name="秀丽倩倩2.0"),
            Voice(voice_id="ICL_uranus_zh_female_yuanqitianmei_tob", name="元气甜妹2.0"),
            Voice(voice_id="ICL_uranus_zh_female_zhixingwenwan_tob", name="知性温婉2.0"),
            Voice(voice_id="ICL_uranus_zh_female_zhixinjiejie_tob", name="知心姐姐2.0"),
            Voice(voice_id="ICL_uranus_zh_male_anrenqinzhu_tob", name="黯刃秦主2.0"),
            Voice(voice_id="ICL_uranus_zh_male_aojiaogongzi_tob", name="傲娇公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_aojiaojingying_tob", name="傲娇精英2.0"),
            Voice(voice_id="ICL_uranus_zh_male_aomanqingnian_tob", name="傲慢青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_aomanshaoye_tob", name="傲慢少爷2.0"),
            Voice(voice_id="ICL_uranus_zh_male_aoqilingren_tob", name="傲气凌人2.0"),
            Voice(voice_id="ICL_uranus_zh_male_badaoshaoye_tob", name="霸道少爷2.0"),
            Voice(voice_id="ICL_uranus_zh_male_badaozongcai_tob", name="霸道总裁2.0"),
            Voice(voice_id="ICL_uranus_zh_male_bingjiaobailian_tob", name="病娇白莲2.0"),
            Voice(voice_id="ICL_uranus_zh_male_bingjiaodidi_tob", name="病娇弟弟2.0"),
            Voice(voice_id="ICL_uranus_zh_male_bingjiaogege_tob", name="病娇哥哥2.0"),
            Voice(voice_id="ICL_uranus_zh_male_bingjiaonanyou_tob", name="病娇男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_bingjiaoshaonian_tob", name="病娇少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_bingruogongzi_tob", name="病弱公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_bingruoshaonian_tob", name="病弱少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_bujiqingnian_tob", name="不羁青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_chanruoshaoye_tob", name="孱弱少爷2.0"),
            Voice(voice_id="ICL_uranus_zh_male_chengshuzongcai_tob", name="成熟总裁2.0"),
            Voice(voice_id="ICL_uranus_zh_male_chenwenmingzai_tob", name="沉稳明仔2.0"),
            Voice(voice_id="ICL_uranus_zh_male_chenwenyouya_tob", name="沉稳优雅2.0"),
            Voice(voice_id="ICL_uranus_zh_male_chunhoudiyin_tob", name="醇厚低音2.0"),
            Voice(voice_id="ICL_uranus_zh_male_chunzhenxuedi_tob", name="纯真学弟2.0"),
            Voice(voice_id="ICL_uranus_zh_male_cixingnansang_tob", name="磁性男嗓2.0"),
            Voice(voice_id="ICL_uranus_zh_male_cujingnansheng_tob", name="醋精男生2.0"),
            Voice(voice_id="ICL_uranus_zh_male_cujingnanyou_tob", name="醋精男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_dichenqianquan_tob", name="低沉缱绻2.0"),
            Voice(voice_id="ICL_uranus_zh_male_diyinchenyu_tob", name="低音沉郁2.0"),
            Voice(voice_id="ICL_uranus_zh_male_fengfashaonian_tob", name="风发少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_fuheigongzi_tob", name="腹黑公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_ganjingshaonian_tob", name="干净少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_gaolengzongcai_tob", name="高冷总裁2.0"),
            Voice(voice_id="ICL_uranus_zh_male_guaogongzi_tob", name="孤傲公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_guayanxiaoge_tob", name="寡言小哥2.0"),
            Voice(voice_id="ICL_uranus_zh_male_gugaogongzi_tob", name="孤高公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_guiyishenmi_tob", name="诡异神秘2.0"),
            Voice(voice_id="ICL_uranus_zh_male_guzhibingjiao_tob", name="固执病娇2.0"),
            Voice(voice_id="ICL_uranus_zh_male_hanhoudunshi_tob", name="憨厚敦实2.0"),
            Voice(voice_id="ICL_uranus_zh_male_huoliqingnian_tob", name="活力青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_huoponanyou_tob", name="活泼男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_huoposhuanglang_tob", name="活泼爽朗2.0"),
            Voice(voice_id="ICL_uranus_zh_male_huzishushu_tob", name="胡子叔叔2.0"),
            Voice(voice_id="ICL_uranus_zh_male_jijiazhineng_tob", name="机甲智能2.0"),
            Voice(voice_id="ICL_uranus_zh_male_jilingxiaohuo_tob", name="机灵小伙2.0"),
            Voice(voice_id="ICL_uranus_zh_male_jingyingqingnian_tob", name="精英青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_junyigongzi_tob", name="俊逸公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_kailangqingkuai_tob", name="开朗轻快2.0"),
            Voice(voice_id="ICL_uranus_zh_male_kailangqingnian_tob", name="开朗青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lanyincaohunshi_tob", name="蓝银草魂师2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lengaozongcai_tob", name="冷傲总裁2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lengdanshuli_tob", name="冷淡疏离2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lengjungaozhi_tob", name="冷峻高智2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lengjunshangsi_tob", name="冷峻上司2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lengkugege_tob", name="冷酷哥哥2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lenglianxiongzhang_tob",
                  name="冷脸兄长2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lenglianxueba_tob", name="冷脸学霸2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lengmonanyou_tob", name="冷漠男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lengmoxiongzhang_tob", name="冷漠兄长2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lingyunqingnian_tob", name="凌云青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_lvchaxiaoge_tob", name="绿茶小哥2.0"),
            Voice(voice_id="ICL_uranus_zh_male_mengdongqingnian_tob", name="懵懂青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_menyoupingxiaoge_tob",
                  name="闷油瓶小哥2.0"),
            Voice(voice_id="ICL_uranus_zh_male_naiqixiaosheng_tob", name="奶气小生2.0"),
            Voice(voice_id="ICL_uranus_zh_male_neiliancaijun_tob", name="内敛才俊2.0"),
            Voice(voice_id="ICL_uranus_zh_male_nianrennanyou_tob", name="粘人男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_nuanxintitie_tob", name="暖心体贴2.0"),
            Voice(voice_id="ICL_uranus_zh_male_paoxiaoxiaoge_tob", name="咆哮小哥2.0"),
            Voice(voice_id="ICL_uranus_zh_male_pianpiangongzi_tob", name="翩翩公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qinglangwenrun_tob", name="清朗温润2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qinglengjingui_tob", name="清冷矜贵2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qingseqingnian_tob", name="青涩青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qingsexiaosheng_tob", name="青涩小生2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qingshuangshaonian_tob",
                  name="清爽少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qingxinbobo_tob", name="清新波波2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qingxinmumu_tob", name="清新沐沐2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qingyisugan_tob", name="清逸苏感2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qinqieqingnian_tob", name="亲切青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_qinqiexiaozhuo_tob", name="亲切小卓2.0"),
            Voice(voice_id="ICL_uranus_zh_male_rexueshaonian_tob", name="热血少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_ruyacaijun_tob", name="儒雅才俊2.0"),
            Voice(voice_id="ICL_uranus_zh_male_ruyagongzi_tob", name="儒雅公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_ruyajunzi_tob", name="儒雅君子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_ruyazongcai_tob", name="儒雅总裁2.0"),
            Voice(voice_id="ICL_uranus_zh_male_sajiaonansheng_tob", name="撒娇男生2.0"),
            Voice(voice_id="ICL_uranus_zh_male_sajiaonanyou_tob", name="撒娇男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_sajiaonianren_tob", name="撒娇粘人2.0"),
            Voice(voice_id="ICL_uranus_zh_male_satuoqingnian_tob", name="洒脱青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_shaonianjiangjun_tob", name="少年将军2.0"),
            Voice(voice_id="ICL_uranus_zh_male_shenchenzongcai_tob", name="深沉总裁2.0"),
            Voice(voice_id="ICL_uranus_zh_male_shenmifashi_tob", name="神秘法师2.0"),
            Voice(voice_id="ICL_uranus_zh_male_shuaizhenxiaohuo_tob", name="率真小伙2.0"),
            Voice(voice_id="ICL_uranus_zh_male_shuanglangshaonian_tob",
                  name="爽朗少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_shuanglangxiaoyang_tob",
                  name="爽朗小阳2.0"),
            Voice(voice_id="ICL_uranus_zh_male_siwenqingnian_tob", name="斯文青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_tiancaitongzhuo_tob", name="天才同桌2.0"),
            Voice(voice_id="ICL_uranus_zh_male_tianxinanyou_tob", name="甜系男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_tiexinnanyou_tob", name="贴心男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_wennuanshaonian_tob", name="温暖少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_wenrounantongzhuo_tob",
                  name="温柔男同桌2.0"),
            Voice(voice_id="ICL_uranus_zh_male_wenrounanyou_tob", name="温柔男友2.0"),
            Voice(voice_id="ICL_uranus_zh_male_wenrouneilian_tob", name="温柔内敛2.0"),
            Voice(voice_id="ICL_uranus_zh_male_wenrouxuezhang_tob", name="温柔学长2.0"),
            Voice(voice_id="ICL_uranus_zh_male_wenrunxuezhe_tob", name="温润学者2.0"),
            Voice(voice_id="ICL_uranus_zh_male_wenshunshaonian_tob", name="温顺少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_xiaohouye_tob", name="小侯爷2.0"),
            Voice(voice_id="ICL_uranus_zh_male_xiaosasuixing_tob", name="潇洒随性2.0"),
            Voice(voice_id="ICL_uranus_zh_male_xiaozhangxiaoge_tob", name="嚣张小哥2.0"),
            Voice(voice_id="ICL_uranus_zh_male_xuebanantongzhuo_tob",
                  name="学霸男同桌2.0"),
            Voice(voice_id="ICL_uranus_zh_male_xuebatongzhuo_tob", name="学霸同桌2.0"),
            Voice(voice_id="ICL_uranus_zh_male_yangguangyangyang_tob", name="阳光洋洋2.0"),
            Voice(voice_id="ICL_uranus_zh_male_yangyang_tob", name="炀炀2.0"),
            Voice(voice_id="ICL_uranus_zh_male_yiqishaonian_tob", name="意气少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_youmodaye_tob", name="幽默大爷2.0"),
            Voice(voice_id="ICL_uranus_zh_male_youmoshushu_tob", name="幽默叔叔2.0"),
            Voice(voice_id="ICL_uranus_zh_male_younidashu_tob", name="油腻大叔2.0"),
            Voice(voice_id="ICL_uranus_zh_male_youroubangzhu_tob", name="优柔帮主2.0"),
            Voice(voice_id="ICL_uranus_zh_male_yourougongzi_tob", name="优柔公子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_yuanqishaonian_tob", name="元气少年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_zhangjianjunzi_tob", name="仗剑君子2.0"),
            Voice(voice_id="ICL_uranus_zh_male_zhangjianxiake_tob", name="仗剑侠客2.0"),
            Voice(voice_id="ICL_uranus_zh_male_zhenbiandiyu_tob", name="枕边低语2.0"),
            Voice(voice_id="ICL_uranus_zh_male_zhengzhiqingnian_tob", name="正直青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_zhishuaiqingnian_tob", name="直率青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_zhongerqingnian_tob", name="中二青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_zifuqingnian_tob", name="自负青年2.0"),
            Voice(voice_id="ICL_uranus_zh_male_zixinqingnian_tob", name="自信青年2.0"),
            Voice(voice_id="zh_female_cancan_uranus_bigtts", name="知性灿灿2.0"),
            Voice(voice_id="zh_female_chanmeinv_uranus_bigtts", name="谄媚女声2.0"),
            Voice(voice_id="zh_female_chunribu_uranus_bigtts", name="春日部姐姐2.0"),
            Voice(voice_id="zh_female_ganmaodianyin_uranus_bigtts",
                  name="感冒电音姐姐2.0"),
            Voice(voice_id="zh_female_gaolengyujie_uranus_bigtts", name="高冷御姐2.0"),
            Voice(voice_id="zh_female_gufengshaoyu_uranus_bigtts", name="古风少御2.0"),
            Voice(voice_id="zh_female_gujie_uranus_bigtts", name="顾姐2.0"),
            Voice(voice_id="zh_female_jiaochuannv_uranus_bigtts", name="娇喘女声2.0"),
            Voice(voice_id="zh_female_jitangmei_uranus_bigtts", name="鸡汤妹妹2.0"),
            Voice(voice_id="zh_female_jitangnv_uranus_bigtts", name="鸡汤女2.0"),
            Voice(voice_id="zh_female_kailangjiejie_uranus_bigtts", name="开朗姐姐2.0"),
            Voice(voice_id="zh_female_kefunvsheng_uranus_bigtts", name="暖阳女声2.0"),
            Voice(voice_id="zh_female_lingling_uranus_bigtts", name="玲玲姐姐2.0"),
            Voice(voice_id="zh_female_linjianvhai_uranus_bigtts", name="邻家女孩2.0"),
            Voice(voice_id="zh_female_linxiao_uranus_bigtts", name="林潇2.0"),
            Voice(voice_id="zh_female_liuchangnv_uranus_bigtts", name="流畅女声2.0"),
            Voice(voice_id="zh_female_meilinvyou_uranus_bigtts", name="魅力女友2.0"),
            Voice(voice_id="zh_female_mengyatou_uranus_bigtts", name="萌丫头2.0"),
            Voice(voice_id="zh_female_mizai_uranus_bigtts", name="黑猫侦探社咪仔2.0"),
            Voice(voice_id="zh_female_nvleishen_uranus_bigtts", name="女雷神2.0"),
            Voice(voice_id="zh_female_peiqi_uranus_bigtts", name="佩奇猪2.0"),
            Voice(voice_id="zh_female_popo_uranus_bigtts", name="婆婆2.0"),
            Voice(voice_id="zh_female_qiaopinv_uranus_bigtts", name="俏皮女声2.0"),
            Voice(voice_id="zh_female_qingchezizi_uranus_bigtts", name="清澈梓梓2.0"),
            Voice(voice_id="zh_female_qingxinnvsheng_uranus_bigtts", name="清新女声2.0"),
            Voice(voice_id="zh_female_qinqienv_uranus_bigtts", name="亲切女声2.0"),
            Voice(voice_id="zh_female_roumeinvyou_uranus_bigtts", name="柔美女友2.0"),
            Voice(voice_id="zh_female_sajiaoxuemei_uranus_bigtts", name="撒娇学妹2.0"),
            Voice(voice_id="zh_female_shaoergushi_uranus_bigtts", name="少儿故事2.0"),
            Voice(voice_id="zh_female_shuangkuaisisi_uranus_bigtts", name="爽快思思2.0"),
            Voice(voice_id="zh_female_sophie_uranus_bigtts", name="魅力苏菲2.0"),
            Voice(voice_id="zh_female_tianmeitaozi_uranus_bigtts", name="甜美桃子2.0"),
            Voice(voice_id="zh_female_tianmeixiaoyuan_uranus_bigtts", name="甜美小源2.0"),
            Voice(voice_id="zh_female_tianmeiyueyue_uranus_bigtts", name="甜美悦悦2.0"),
            Voice(voice_id="zh_female_tiexinnvsheng_uranus_bigtts", name="贴心女声2.0"),
            Voice(voice_id="zh_female_tvbnv_uranus_bigtts", name="TVB女声2.0"),
            Voice(voice_id="zh_female_vv_uranus_bigtts", name="Vivi2.0"),
            Voice(voice_id="zh_female_wenjingmaomao_uranus_bigtts", name="文静毛毛2.0"),
            Voice(voice_id="zh_female_wenroumama_uranus_bigtts", name="温柔妈妈2.0"),
            Voice(voice_id="zh_female_wenroushunv_uranus_bigtts", name="温柔淑女2.0"),
            Voice(voice_id="zh_female_wenrouxiaoya_uranus_bigtts", name="温柔小雅2.0"),
            Voice(voice_id="zh_female_wuzetian_uranus_bigtts", name="武则天2.0"),
            Voice(voice_id="zh_female_xiaohe_uranus_bigtts", name="小何2.0"),
            Voice(voice_id="zh_female_xiaoxue_uranus_bigtts", name="儿童绘本2.0"),
            Voice(voice_id="zh_female_xinlingjitang_uranus_bigtts", name="心灵鸡汤2.0"),
            Voice(voice_id="zh_female_yingtaowanzi_uranus_bigtts", name="樱桃丸子2.0"),
            Voice(voice_id="zh_female_yingyujiaoxue_uranus_bigtts",
                  name="Tina老师2.0"),
            Voice(voice_id="zh_female_zhishuaiyingzi_uranus_bigtts", name="直率英子2.0"),
            Voice(voice_id="zh_female_zhixingnv_uranus_bigtts", name="知性女声2.0"),
            Voice(voice_id="zh_male_aojiaobazong_uranus_bigtts", name="傲娇霸总2.0"),
            Voice(voice_id="zh_male_baqiqingshu_uranus_bigtts", name="霸气青叔2.0"),
            Voice(voice_id="zh_male_cixingjieshuonan_uranus_bigtts",
                  name="磁性解说男声2.0"),
            Voice(voice_id="zh_male_dayi_uranus_bigtts", name="大壹2.0"),
            Voice(voice_id="zh_male_dongfanghaoran_uranus_bigtts", name="东方浩然2.0"),
            Voice(voice_id="zh_male_fanjuanqingnian_uranus_bigtts", name="反卷青年2.0"),
            Voice(voice_id="zh_male_gaolengchenwen_uranus_bigtts", name="高冷沉稳2.0"),
            Voice(voice_id="zh_male_guanggaojieshuo_uranus_bigtts", name="广告解说2.0"),
            Voice(voice_id="zh_male_huolixiaoge_uranus_bigtts", name="活力小哥2.0"),
            Voice(voice_id="zh_male_jieshuoxiaoming_uranus_bigtts", name="解说小明2.0"),
            Voice(voice_id="zh_male_kailangdidi_uranus_bigtts", name="开朗弟弟2.0"),
            Voice(voice_id="zh_male_kailangxuezhang_uranus_bigtts", name="开朗学长2.0"),
            Voice(voice_id="zh_male_kuailexiaodong_uranus_bigtts", name="快乐小东2.0"),
            Voice(voice_id="zh_male_lanyinmianbao_uranus_bigtts", name="懒音绵宝2.0"),
            Voice(voice_id="zh_male_liangsangmengzai_uranus_bigtts", name="亮嗓萌仔2.0"),
            Voice(voice_id="zh_male_linjiananhai_uranus_bigtts", name="邻家男孩2.0"),
            Voice(voice_id="zh_male_liufei_uranus_bigtts", name="刘飞2.0"),
            Voice(voice_id="zh_male_lubanqihao_uranus_bigtts", name="鲁班七号2.0"),
            Voice(voice_id="zh_male_m191_uranus_bigtts", name="云舟2.0"),
            Voice(voice_id="zh_male_naiqimengwa_uranus_bigtts", name="奶气萌娃2.0"),
            Voice(voice_id="zh_male_qingcang_uranus_bigtts", name="擎苍2.0"),
            Voice(voice_id="zh_male_qingshuangnanda_uranus_bigtts", name="清爽男大2.0"),
            Voice(voice_id="zh_male_ruyaqingnian_uranus_bigtts", name="儒雅青年2.0"),
            Voice(voice_id="zh_male_ruyayichen_uranus_bigtts", name="儒雅逸辰2.0"),
            Voice(voice_id="zh_male_shaonianzixin_uranus_bigtts", name="少年梓辛2.0"),
            Voice(voice_id="zh_male_shenyeboke_uranus_bigtts", name="深夜播客2.0"),
            Voice(voice_id="zh_male_silang_uranus_bigtts", name="四郎2.0"),
            Voice(voice_id="zh_male_sunwukong_uranus_bigtts", name="猴哥2.0"),
            Voice(voice_id="zh_male_tangseng_uranus_bigtts", name="唐僧2.0"),
            Voice(voice_id="zh_male_taocheng_uranus_bigtts", name="小天2.0"),
            Voice(voice_id="zh_male_tiancaitongsheng_uranus_bigtts", name="天才童声2.0"),
            Voice(voice_id="zh_male_wennuanahu_uranus_bigtts", name="温暖阿虎2.0"),
            Voice(voice_id="zh_male_wenrouxiaoge_uranus_bigtts", name="温柔小哥2.0"),
            Voice(voice_id="zh_male_xionger_uranus_bigtts", name="熊二2.0"),
            Voice(voice_id="zh_male_xuanyijieshuo_uranus_bigtts", name="悬疑解说2.0"),
            Voice(voice_id="zh_male_yangguangqingnian_uranus_bigtts", name="阳光青年2.0"),
            Voice(voice_id="zh_male_yizhipiannan_uranus_bigtts", name="译制片男2.0"),
            Voice(voice_id="zh_male_youyoujunzi_uranus_bigtts", name="悠悠君子2.0"),
            Voice(voice_id="zh_male_yuanboxiaoshu_uranus_bigtts", name="渊博小叔2.0"),
            Voice(voice_id="zh_male_zhuangzhou_uranus_bigtts", name="庄周2.0"),
            Voice(voice_id="zh_male_zhubajie_uranus_bigtts", name="猪八戒2.0"),
        ],
        "ja-JP": [
            Voice(voice_id="ja_female_bv024_uranus_bigtts", name="Bonnie"),
            Voice(voice_id="ja_female_bv520_uranus_bigtts", name="Poppy"),
            Voice(voice_id="ja_female_bv521_uranus_bigtts", name="Aoi"),
            Voice(voice_id="ja_female_bv522_uranus_bigtts", name="Hana"),
            Voice(voice_id="ja_female_bv523_uranus_bigtts", name="Lily"),
            Voice(voice_id="ja_female_minimi_uranus_bigtts", name="Minimi"),
            Voice(voice_id="ja_female_shirou_uranus_bigtts", name="Shirou"),
            Voice(voice_id="ja_male_bv524_uranus_bigtts", name="Ken"),
            Voice(voice_id="zh_female_vv_uranus_bigtts", name="Vivi2.0"),
        ],
        "id-ID": [
            Voice(voice_id="id_female_bv161_uranus_bigtts", name="Clara"),
            Voice(voice_id="id_female_bv161dialogue_uranus_bigtts", name="Sylvia"),
            Voice(voice_id="id_female_bv161narration_uranus_bigtts", name="Celeste"),
            Voice(voice_id="id_female_bv164_uranus_bigtts", name="Crew"),
            Voice(voice_id="id_female_f20_uranus_bigtts", name="Chloe"),
            Voice(voice_id="id_female_phulia_uranus_bigtts", name="Phulia"),
            Voice(voice_id="id_male_bv160_uranus_bigtts", name="Rocco"),
            Voice(voice_id="id_male_bv160dialogue_uranus_bigtts", name="Jude"),
            Voice(voice_id="id_male_bv160narration_uranus_bigtts", name="Hugo"),
            Voice(voice_id="id_male_bv164dialogue_uranus_bigtts", name="Elian"),
            Voice(voice_id="id_male_bv164narration_uranus_bigtts", name="Ronan"),
            Voice(voice_id="id_male_han_uranus_bigtts", name="Han"),
            Voice(voice_id="id_male_m08_uranus_bigtts", name="Kyle"),
            Voice(voice_id="zh_female_vv_uranus_bigtts", name="Vivi2.0"),
        ],
        "es-MX": [
            Voice(voice_id="zh_female_vv_uranus_bigtts", name="Vivi2.0"),
        ],
        "en-GB": [
            Voice(voice_id="ICL_uranus_en_male_alastor_tob", name="Alastor2.0"),
            Voice(voice_id="zh_female_yingyujiaoxue_uranus_bigtts",
                  name="Tina老师2.0"),
        ],
        "en-US": [
            Voice(voice_id="ICL_uranus_en_female_charlie_tob", name="Charlie2.0"),
            Voice(voice_id="ICL_uranus_en_male_big_boogie_tob",
                  name="BigBoogie2.0"),
            Voice(voice_id="ICL_uranus_en_male_cartoon_chef_tob",
                  name="CartoonChef2.0"),
            Voice(voice_id="ICL_uranus_en_male_chucky_tob", name="Chucky2.0"),
            Voice(voice_id="ICL_uranus_en_male_clown_man_tob", name="ClownMan2.0"),
            Voice(voice_id="ICL_uranus_en_male_frosty_man_tob",
                  name="FrostyMan2.0"),
            Voice(voice_id="ICL_uranus_en_male_jigsaw_tob", name="Jigsaw2.0"),
            Voice(voice_id="ICL_uranus_en_male_kevin_mccallister_tob",
                  name="KevinMcCallister2.0"),
            Voice(voice_id="ICL_uranus_en_male_michael_tob", name="Michael2.0"),
            Voice(voice_id="ICL_uranus_en_male_noah_tob", name="Noah2.0"),
            Voice(voice_id="ICL_uranus_en_male_the_grinch_tob",
                  name="TheGrinch2.0"),
            Voice(voice_id="ICL_uranus_en_male_xavier_tob", name="Xavier2.0"),
            Voice(voice_id="ICL_uranus_en_male_zayne_tob", name="Zayne2.0"),
            Voice(voice_id="en_female_allison_uranus_bigtts", name="Allison"),
            Voice(voice_id="en_female_authoritative-british_uranus_bigtts",
                  name="Charlotte"),
            Voice(
                voice_id="en_female_authoritative-informative_uranus_bigtts", name="Margaret"),
            Voice(voice_id="en_female_brittney_pimintel_uranus_bigtts", name="Zoe"),
            Voice(voice_id="en_female_brittney_uranus_bigtts", name="Brittney"),
            Voice(voice_id="en_female_dacey_uranus_bigtts", name="Dacey"),
            Voice(voice_id="en_female_female_tutor_ms-jenny_uranus_bigtts", name="Holly"),
            Voice(voice_id="en_female_hayley_uranus_bigtts", name="Hayley"),
            Voice(voice_id="en_female_jane_uranus_bigtts", name="Jane"),
            Voice(voice_id="en_female_jenny_uranus_bigtts", name="Jenny"),
            Voice(voice_id="en_female_joanne_uranus_bigtts", name="Joanne"),
            Voice(
                voice_id="en_female_lana_del_rey_kelley_d_p1_uranus_bigtts", name="Lynn"),
            Voice(voice_id="en_female_lana_del_rey_parky_s_p1_uranus_bigtts", name="Ivy"),
            Voice(voice_id="en_female_mel_uranus_bigtts", name="Mel"),
            Voice(voice_id="en_female_myra_cmb_uranus_bigtts", name="Sunny"),
            Voice(voice_id="en_female_myra_uranus_bigtts", name="Myra"),
            Voice(voice_id="en_female_nadia_uranus_bigtts", name="Blair"),
            Voice(voice_id="en_female_natasha_uranus_bigtts", name="Natasha"),
            Voice(voice_id="en_female_pleasant-female_uranus_bigtts", name="Elaine"),
            Voice(voice_id="en_female_rachel_p1_uranus_bigtts", name="Rachel"),
            Voice(voice_id="en_female_scarlet_p1_uranus_bigtts", name="Scarlet"),
            Voice(voice_id="en_female_sharron_uranus_bigtts", name="Sharron"),
            Voice(voice_id="en_female_skye_uranus_bigtts", name="Skye"),
            Voice(voice_id="en_female_stokie_uranus_bigtts", name="Stokie"),
            Voice(voice_id="en_female_wenrouzhishijieshuonv_uranus_bigtts", name="Megan"),
            Voice(voice_id="en_female_xinwenjieshuonv_uranus_bigtts", name="Kayla"),
            Voice(voice_id="en_female_zendaya_p1_uranus_bigtts", name="Zendaya"),
            Voice(voice_id="en_male_adam-imitation_uranus_bigtts", name="Rowan"),
            Voice(voice_id="en_male_alberto_uranus_bigtts", name="Alberto"),
            Voice(voice_id="en_male_alex_uranus_bigtts", name="Alex"),
            Voice(voice_id="en_male_bill-jones_uranus_bigtts", name="Jones"),
            Voice(voice_id="en_male_bill_jones_corey_uranus_bigtts", name="Bill"),
            Voice(voice_id="en_male_brad_pitt_p1_uranus_bigtts", name="Brad_Pitt"),
            Voice(voice_id="en_male_bruce_uranus_bigtts", name="Adrian"),
            Voice(voice_id="en_male_chandler_p1_uranus_bigtts", name="Leo"),
            Voice(voice_id="en_male_cowboy-bob_uranus_bigtts", name="Bob"),
            Voice(voice_id="en_male_cowboy_john_b_uranus_bigtts", name="John"),
            Voice(voice_id="en_male_david_uranus_bigtts", name="David"),
            Voice(voice_id="en_male_deep-voice_uranus_bigtts", name="Orion"),
            Voice(voice_id="en_male_diyuwenrounan_uranus_bigtts", name="Julian"),
            Voice(voice_id="en_male_evil-guy-oxley_uranus_bigtts", name="Harrison"),
            Voice(voice_id="en_male_excited-male-voice_uranus_bigtts", name="Jasper"),
            Voice(voice_id="en_male_father-christmas_uranus_bigtts", name="Alfred"),
            Voice(voice_id="en_male_fernando-martinez_uranus_bigtts", name="Felix"),
            Voice(voice_id="en_male_godfather_uranus_bigtts", name="Godfather"),
            Voice(voice_id="en_male_gollum_uranus_bigtts", name="Gollum"),
            Voice(voice_id="en_male_hades_uranus_bigtts", name="Beau"),
            Voice(voice_id="en_male_jamie_uranus_bigtts", name="Jamie"),
            Voice(voice_id="en_male_jidongchuanjiaoshi_uranus_bigtts", name="Blaze"),
            Voice(voice_id="en_male_jimmy_uranus_bigtts", name="Jimmy"),
            Voice(voice_id="en_male_joker_uranus_bigtts", name="Joker"),
            Voice(voice_id="en_male_josh_coery_uranus_bigtts", name="Josiah"),
            Voice(voice_id="en_male_josh_uranus_bigtts", name="Josh"),
            Voice(voice_id="en_male_kevin_uranus_bigtts", name="Kevin"),
            Voice(voice_id="en_male_knightley_uranus_bigtts", name="Knightley"),
            Voice(voice_id="en_male_marcus_uranus_bigtts", name="Marcus"),
            Voice(voice_id="en_male_michael-mouse_uranus_bigtts", name="Chip"),
            Voice(voice_id="en_male_michael_kevin_uranus_bigtts",
                  name="Michael_Kevin"),
            Voice(voice_id="en_male_michael_uranus_bigtts", name="Hank"),
            Voice(voice_id="en_male_motivational-coach_uranus_bigtts", name="Rory"),
            Voice(voice_id="en_male_ronald_uranus_bigtts", name="Ronald"),
            Voice(voice_id="en_male_russell_uranus_bigtts", name="Russell"),
            Voice(voice_id="en_male_simba_p1_uranus_bigtts", name="Simba"),
            Voice(voice_id="en_male_tim_uranus_bigtts", name="Tim"),
            Voice(voice_id="en_male_tom_hiddleston_p1_uranus_bigtts", name="Tom"),
            Voice(voice_id="en_male_valentino_corey_uranus_bigtts", name="Clark"),
            Voice(voice_id="en_male_valentino_uranus_bigtts", name="Valentino"),
            Voice(voice_id="en_male_yangguangjieshuonan_uranus_bigtts", name="Dylan"),
        ],
        "es-ES": [
            Voice(voice_id="mx_female_bv065_uranus_bigtts", name="Irene"),
            Voice(voice_id="mx_female_bv166dialogue_uranus_bigtts", name="Lucy"),
            Voice(voice_id="mx_female_bv166emotion_uranus_bigtts", name="Rosa"),
            Voice(voice_id="mx_female_bv166narrator_uranus_bigtts", name="Freya"),
            Voice(voice_id="mx_female_leslie_uranus_bigtts", name="Leslie"),
            Voice(voice_id="mx_male_bv165dialogue_uranus_bigtts", name="Diego"),
            Voice(voice_id="mx_male_bv165narrator_uranus_bigtts", name="Marcos"),
            Voice(voice_id="mx_male_felipe_uranus_bigtts", name="Felipe"),
            Voice(voice_id="mx_male_ht_mx_m012_uranus_bigtts", name="Derek"),
            Voice(voice_id="mx_male_marcelo_uranus_bigtts", name="Marcelo"),
        ],
    },
    "seed-tts-1.0": {
        "zh-CN": [
            Voice(voice_id="en_male_jason_conversation_wvae_bigtts", name="开朗学长"),
            Voice(voice_id="zh_female_cancan_mars_bigtts", name="灿灿/Shiny"),
            Voice(voice_id="zh_female_daimengchuanmei_moon_bigtts", name="呆萌川妹"),
            Voice(voice_id="zh_female_flattery_mars_bigtts", name="谄媚女声"),
            Voice(voice_id="zh_female_ganmaodianyin_mars_bigtts", name="感冒电音姐姐"),
            Voice(voice_id="zh_female_gaolengyujie_emo_v2_mars_bigtts",
                  name="高冷御姐（多情感）"),
            Voice(voice_id="zh_female_gaolengyujie_moon_bigtts", name="高冷御姐"),
            Voice(voice_id="zh_female_gufengshaoyu_mars_bigtts", name="古风少御"),
            Voice(voice_id="zh_female_gujie_mars_bigtts", name="顾姐"),
            Voice(voice_id="zh_female_jiaochuan_mars_bigtts", name="娇喘女声"),
            Voice(voice_id="zh_female_jitangmeimei_mars_bigtts", name="鸡汤妹妹/Hope"),
            Voice(voice_id="zh_female_jiyejizi2_mars_bigtts", name="春日部姐姐"),
            Voice(voice_id="zh_female_kailangjiejie_moon_bigtts", name="开朗姐姐"),
            Voice(voice_id="zh_female_kefunvsheng_mars_bigtts", name="暖阳女声"),
            Voice(voice_id="zh_female_leidian_mars_bigtts", name="女雷神"),
            Voice(voice_id="zh_female_linjianvhai_moon_bigtts", name="邻家女孩"),
            Voice(voice_id="zh_female_linjuayi_emo_v2_mars_bigtts",
                  name="邻居阿姨（多情感）"),
            Voice(voice_id="zh_female_linzhiling_mars_bigtts", name="玲玲姐姐"),
            Voice(voice_id="zh_female_maomao_conversation_wvae_bigtts", name="文静毛毛"),
            Voice(voice_id="zh_female_meilinvyou_emo_v2_mars_bigtts",
                  name="魅力女友（多情感）"),
            Voice(voice_id="zh_female_meilinvyou_moon_bigtts", name="魅力女友"),
            Voice(voice_id="zh_female_meituojieer_moon_bigtts", name="妹坨洁儿"),
            Voice(voice_id="zh_female_mengyatou_mars_bigtts", name="萌丫头/Cutey"),
            Voice(voice_id="zh_female_naying_mars_bigtts", name="直率英子"),
            Voice(voice_id="zh_female_peiqi_mars_bigtts", name="佩奇猪"),
            Voice(voice_id="zh_female_popo_mars_bigtts", name="婆婆"),
            Voice(voice_id="zh_female_qiaopinvsheng_mars_bigtts", name="俏皮女声"),
            Voice(voice_id="zh_female_qingchezizi_moon_bigtts", name="清澈梓梓"),
            Voice(voice_id="zh_female_qingxinnvsheng_mars_bigtts", name="清新女声"),
            Voice(voice_id="zh_female_qinqienvsheng_moon_bigtts", name="亲切女声"),
            Voice(voice_id="zh_female_roumeinvyou_emo_v2_mars_bigtts",
                  name="柔美女友（多情感）"),
            Voice(voice_id="zh_female_sajiaonvyou_moon_bigtts", name="柔美女友"),
            Voice(voice_id="zh_female_shaoergushi_mars_bigtts", name="少儿故事"),
            Voice(voice_id="zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
                  name="爽快思思（多情感）"),
            Voice(voice_id="zh_female_shuangkuaisisi_moon_bigtts", name="爽快思思/Skye"),
            Voice(voice_id="zh_female_sophie_conversation_wvae_bigtts", name="魅力苏菲"),
            Voice(voice_id="zh_female_tianmeitaozi_mars_bigtts", name="甜美桃子"),
            Voice(voice_id="zh_female_tianmeixiaoyuan_moon_bigtts", name="甜美小源"),
            Voice(voice_id="zh_female_tianmeiyueyue_moon_bigtts", name="甜美悦悦"),
            Voice(voice_id="zh_female_tianxinxiaomei_emo_v2_mars_bigtts",
                  name="甜心小美（多情感）"),
            Voice(voice_id="zh_female_tiexinnvsheng_mars_bigtts", name="贴心女声/Candy"),
            Voice(voice_id="zh_female_vv_mars_bigtts", name="Vivi"),
            Voice(voice_id="zh_female_wanqudashu_moon_bigtts", name="湾区大叔"),
            Voice(voice_id="zh_female_wanwanxiaohe_moon_bigtts", name="湾湾小何"),
            Voice(voice_id="zh_female_wenroushunv_mars_bigtts", name="温柔淑女"),
            Voice(voice_id="zh_female_wenrouxiaoya_moon_bigtts", name="温柔小雅"),
            Voice(voice_id="zh_female_wuzetian_mars_bigtts", name="武则天"),
            Voice(voice_id="zh_female_xinlingjitang_moon_bigtts", name="心灵鸡汤"),
            Voice(voice_id="zh_female_yangmi_mars_bigtts", name="林潇"),
            Voice(voice_id="zh_female_yingtaowanzi_mars_bigtts", name="樱桃丸子"),
            Voice(voice_id="zh_female_yingyujiaoyu_mars_bigtts", name="Tina老师"),
            Voice(voice_id="zh_female_yuanqinvyou_moon_bigtts", name="撒娇学妹"),
            Voice(voice_id="zh_female_yueyunv_mars_bigtts", name="粤语小溏"),
            Voice(voice_id="zh_female_zhixingnvsheng_mars_bigtts", name="知性女声"),
            Voice(voice_id="zh_male_M100_conversation_wvae_bigtts", name="悠悠君子"),
            Voice(voice_id="zh_male_aojiaobazong_emo_v2_mars_bigtts",
                  name="傲娇霸总（多情感）"),
            Voice(voice_id="zh_male_aojiaobazong_moon_bigtts", name="傲娇霸总"),
            Voice(voice_id="zh_male_baqiqingshu_mars_bigtts", name="霸气青叔"),
            Voice(voice_id="zh_male_beijingxiaoye_emo_v2_mars_bigtts",
                  name="北京小爷（多情感）"),
            Voice(voice_id="zh_male_beijingxiaoye_moon_bigtts", name="北京小爷"),
            Voice(voice_id="zh_male_changtianyi_mars_bigtts", name="悬疑解说"),
            Voice(voice_id="zh_male_chunhui_mars_bigtts", name="广告解说"),
            Voice(voice_id="zh_male_dongfanghaoran_moon_bigtts", name="东方浩然"),
            Voice(voice_id="zh_male_dongmanhaimian_mars_bigtts", name="亮嗓萌仔"),
            Voice(voice_id="zh_male_fanjuanqingnian_mars_bigtts", name="反卷青年"),
            Voice(voice_id="zh_male_guangxiyuanzhou_moon_bigtts", name="广西远舟"),
            Voice(voice_id="zh_male_guangzhoudege_emo_mars_bigtts",
                  name="广州德哥（多情感）"),
            Voice(voice_id="zh_male_guozhoudege_moon_bigtts", name="广州德哥"),
            Voice(voice_id="zh_male_haoyuxiaoge_moon_bigtts", name="浩宇小哥"),
            Voice(voice_id="zh_male_hupunan_mars_bigtts", name="沪普男"),
            Voice(voice_id="zh_male_jieshuonansheng_mars_bigtts",
                  name="磁性解说男声/Morgan"),
            Voice(voice_id="zh_male_jieshuoxiaoming_moon_bigtts", name="解说小明"),
            Voice(voice_id="zh_male_jingqiangkanye_emo_mars_bigtts",
                  name="京腔侃爷（多情感）"),
            Voice(voice_id="zh_male_jingqiangkanye_moon_bigtts",
                  name="京腔侃爷/Harmony"),
            Voice(voice_id="zh_male_junlangnanyou_emo_v2_mars_bigtts",
                  name="俊朗男友（多情感）"),
            Voice(voice_id="zh_male_lanxiaoyang_mars_bigtts", name="懒音绵宝"),
            Voice(voice_id="zh_male_lengkugege_emo_v2_mars_bigtts",
                  name="冷酷哥哥（多情感）"),
            Voice(voice_id="zh_male_linjiananhai_moon_bigtts", name="邻家男孩"),
            Voice(voice_id="zh_male_livelybro_mars_bigtts", name="开朗弟弟"),
            Voice(voice_id="zh_male_lubanqihao_mars_bigtts", name="鲁班七号"),
            Voice(voice_id="zh_male_naiqimengwa_mars_bigtts", name="奶气萌娃"),
            Voice(voice_id="zh_male_qingcang_mars_bigtts", name="擎苍"),
            Voice(voice_id="zh_male_qingshuangnanda_mars_bigtts", name="清爽男大"),
            Voice(voice_id="zh_male_qingyiyuxuan_mars_bigtts", name="阳光阿辰"),
            Voice(voice_id="zh_male_ruyaqingnian_mars_bigtts", name="儒雅青年"),
            Voice(voice_id="zh_male_ruyayichen_emo_v2_mars_bigtts",
                  name="儒雅男友（多情感）"),
            Voice(voice_id="zh_male_shaonianzixin_moon_bigtts", name="少年梓辛/Brayan"),
            Voice(voice_id="zh_male_shenyeboke_emo_v2_mars_bigtts", name="深夜播客"),
            Voice(voice_id="zh_male_shenyeboke_moon_bigtts", name="深夜播客"),
            Voice(voice_id="zh_male_silang_mars_bigtts", name="四郎"),
            Voice(voice_id="zh_male_sunwukong_mars_bigtts", name="猴哥"),
            Voice(voice_id="zh_male_tangseng_mars_bigtts", name="唐僧"),
            Voice(voice_id="zh_male_tiancaitongsheng_mars_bigtts", name="天才童声"),
            Voice(voice_id="zh_male_wennuanahu_moon_bigtts", name="温暖阿虎/Alvin"),
            Voice(voice_id="zh_male_wenrouxiaoge_mars_bigtts", name="温柔小哥"),
            Voice(voice_id="zh_male_xionger_mars_bigtts", name="熊二"),
            Voice(voice_id="zh_male_xudong_conversation_wvae_bigtts", name="快乐小东"),
            Voice(voice_id="zh_male_yangguangqingnian_emo_v2_mars_bigtts",
                  name="阳光青年（多情感）"),
            Voice(voice_id="zh_male_yangguangqingnian_mars_bigtts", name="活力小哥"),
            Voice(voice_id="zh_male_yangguangqingnian_moon_bigtts", name="阳光青年"),
            Voice(voice_id="zh_male_yourougongzi_emo_v2_mars_bigtts",
                  name="优柔公子（多情感）"),
            Voice(voice_id="zh_male_yuanboxiaoshu_moon_bigtts", name="渊博小叔"),
            Voice(voice_id="zh_male_yuzhouzixuan_moon_bigtts", name="豫州子轩"),
            Voice(voice_id="zh_male_zhoujielun_emo_v2_mars_bigtts", name="双节棍小哥"),
            Voice(voice_id="zh_male_zhuangzhou_mars_bigtts", name="庄周"),
            Voice(voice_id="zh_male_zhubajie_mars_bigtts", name="猪八戒"),
        ],
        "en-GB": [
            Voice(voice_id="en_female_anna_mars_bigtts", name="Anna"),
            Voice(voice_id="en_female_daisy_moon_bigtts", name="DelicateGirl"),
            Voice(voice_id="en_female_emily_mars_bigtts", name="Emily"),
            Voice(voice_id="en_female_nadia_tips_emo_v2_mars_bigtts", name="Nadia"),
            Voice(voice_id="en_female_onez_moon_bigtts", name="Onez"),
            Voice(voice_id="en_male_corey_emo_v2_mars_bigtts", name="Corey"),
            Voice(voice_id="en_male_dave_moon_bigtts", name="Dave"),
            Voice(voice_id="en_male_hades_moon_bigtts", name="Hades"),
            Voice(voice_id="en_male_smith_mars_bigtts", name="Smith"),
            Voice(voice_id="zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
                  name="爽快思思（多情感）"),
            Voice(voice_id="zh_female_yingyujiaoyu_mars_bigtts", name="Tina老师"),
            Voice(voice_id="zh_male_xudong_conversation_wvae_bigtts", name="Daniel"),
        ],
        "en-US": [
            Voice(voice_id="en_female_amanda_mars_bigtts", name="Amanda"),
            Voice(voice_id="en_female_candice_emo_v2_mars_bigtts", name="Candice"),
            Voice(voice_id="en_female_dacey_conversation_wvae_bigtts", name="Daisy"),
            Voice(voice_id="en_female_emotional_moon_bigtts",
                  name="PeacefulFemale"),
            Voice(voice_id="en_female_lauren_moon_bigtts", name="Lauren"),
            Voice(voice_id="en_female_nara_moon_bigtts", name="Nara"),
            Voice(voice_id="en_female_product_darcie_moon_bigtts",
                  name="FlirtyFemale"),
            Voice(voice_id="en_female_sarah_new_conversation_wvae_bigtts", name="Luna"),
            Voice(voice_id="en_female_skye_emo_v2_mars_bigtts", name="Serena"),
            Voice(voice_id="en_male_adam_mars_bigtts", name="Adam"),
            Voice(voice_id="en_male_bruce_moon_bigtts", name="Bruce"),
            Voice(voice_id="en_male_campaign_jamal_moon_bigtts",
                  name="EnergeticMaleII"),
            Voice(voice_id="en_male_charlie_conversation_wvae_bigtts", name="Owen"),
            Voice(voice_id="en_male_chris_moon_bigtts", name="GothamHero"),
            Voice(voice_id="en_male_glen_emo_v2_mars_bigtts", name="Glen"),
            Voice(voice_id="en_male_jackson_mars_bigtts", name="Jackson"),
            Voice(voice_id="en_male_sylus_emo_v2_mars_bigtts", name="Sylus"),
            Voice(voice_id="zh_female_cancan_mars_bigtts", name="灿灿/Shiny"),
            Voice(voice_id="zh_female_jitangmeimei_mars_bigtts", name="鸡汤妹妹/Hope"),
            Voice(voice_id="zh_female_mengyatou_mars_bigtts", name="萌丫头/Cutey"),
            Voice(voice_id="zh_female_shuangkuaisisi_moon_bigtts", name="爽快思思/Skye"),
            Voice(voice_id="zh_female_sophie_conversation_wvae_bigtts", name="Sophie"),
            Voice(voice_id="zh_female_tiexinnvsheng_mars_bigtts", name="贴心女声/Candy"),
            Voice(voice_id="zh_male_M100_conversation_wvae_bigtts", name="Lucas"),
            Voice(voice_id="zh_male_jieshuonansheng_mars_bigtts",
                  name="磁性解说男声/Morgan"),
            Voice(voice_id="zh_male_jingqiangkanye_moon_bigtts",
                  name="京腔侃爷/Harmony"),
            Voice(voice_id="zh_male_shaonianzixin_moon_bigtts", name="少年梓辛/Brayan"),
            Voice(voice_id="zh_male_wennuanahu_moon_bigtts", name="温暖阿虎/Alvin"),
        ],
        "es-ES": [
            Voice(voice_id="multi_female_maomao_conversation_wvae_bigtts", name="Diana"),
            Voice(voice_id="multi_female_shuangkuaisisi_moon_bigtts",
                  name="はるこ（晴子）/Esmeralda"),
            Voice(voice_id="multi_female_sophie_conversation_wvae_bigtts", name="Sofía"),
            Voice(voice_id="multi_male_M100_conversation_wvae_bigtts", name="Lucía"),
            Voice(voice_id="multi_male_jingqiangkanye_moon_bigtts",
                  name="かずね（和音）/JavierorÁlvaro"),
            Voice(voice_id="multi_male_wanqudashu_moon_bigtts",
                  name="ひろし（広志）/Roberto"),
            Voice(voice_id="multi_male_xudong_conversation_wvae_bigtts",
                  name="Daníel"),
        ],
        "ja-JP": [
            Voice(voice_id="multi_female_gaolengyujie_moon_bigtts", name="あけみ（朱美）"),
            Voice(voice_id="multi_female_maomao_conversation_wvae_bigtts", name="つき（月）"),
            Voice(voice_id="multi_female_shuangkuaisisi_moon_bigtts",
                  name="はるこ（晴子）/Esmeralda"),
            Voice(voice_id="multi_female_sophie_conversation_wvae_bigtts",
                  name="さとみ（智美）"),
            Voice(voice_id="multi_male_jingqiangkanye_moon_bigtts",
                  name="かずね（和音）/JavierorÁlvaro"),
            Voice(voice_id="multi_male_wanqudashu_moon_bigtts",
                  name="ひろし（広志）/Roberto"),
            Voice(voice_id="multi_male_xudong_conversation_wvae_bigtts",
                  name="まさお（正男）"),
            Voice(voice_id="multi_zh_male_youyoujunzi_moon_bigtts", name="ひかる（光）"),
        ],
    },
    "seed-tts-1.0-concurr": {
        "zh-CN": [
            Voice(voice_id="en_male_jason_conversation_wvae_bigtts", name="开朗学长"),
            Voice(voice_id="zh_female_cancan_mars_bigtts", name="灿灿/Shiny"),
            Voice(voice_id="zh_female_daimengchuanmei_moon_bigtts", name="呆萌川妹"),
            Voice(voice_id="zh_female_flattery_mars_bigtts", name="谄媚女声"),
            Voice(voice_id="zh_female_ganmaodianyin_mars_bigtts", name="感冒电音姐姐"),
            Voice(voice_id="zh_female_gaolengyujie_emo_v2_mars_bigtts",
                  name="高冷御姐（多情感）"),
            Voice(voice_id="zh_female_gaolengyujie_moon_bigtts", name="高冷御姐"),
            Voice(voice_id="zh_female_gufengshaoyu_mars_bigtts", name="古风少御"),
            Voice(voice_id="zh_female_gujie_mars_bigtts", name="顾姐"),
            Voice(voice_id="zh_female_jiaochuan_mars_bigtts", name="娇喘女声"),
            Voice(voice_id="zh_female_jitangmeimei_mars_bigtts", name="鸡汤妹妹/Hope"),
            Voice(voice_id="zh_female_jiyejizi2_mars_bigtts", name="春日部姐姐"),
            Voice(voice_id="zh_female_kailangjiejie_moon_bigtts", name="开朗姐姐"),
            Voice(voice_id="zh_female_kefunvsheng_mars_bigtts", name="暖阳女声"),
            Voice(voice_id="zh_female_leidian_mars_bigtts", name="女雷神"),
            Voice(voice_id="zh_female_linjianvhai_moon_bigtts", name="邻家女孩"),
            Voice(voice_id="zh_female_linjuayi_emo_v2_mars_bigtts",
                  name="邻居阿姨（多情感）"),
            Voice(voice_id="zh_female_linzhiling_mars_bigtts", name="玲玲姐姐"),
            Voice(voice_id="zh_female_maomao_conversation_wvae_bigtts", name="文静毛毛"),
            Voice(voice_id="zh_female_meilinvyou_emo_v2_mars_bigtts",
                  name="魅力女友（多情感）"),
            Voice(voice_id="zh_female_meilinvyou_moon_bigtts", name="魅力女友"),
            Voice(voice_id="zh_female_meituojieer_moon_bigtts", name="妹坨洁儿"),
            Voice(voice_id="zh_female_mengyatou_mars_bigtts", name="萌丫头/Cutey"),
            Voice(voice_id="zh_female_naying_mars_bigtts", name="直率英子"),
            Voice(voice_id="zh_female_peiqi_mars_bigtts", name="佩奇猪"),
            Voice(voice_id="zh_female_popo_mars_bigtts", name="婆婆"),
            Voice(voice_id="zh_female_qiaopinvsheng_mars_bigtts", name="俏皮女声"),
            Voice(voice_id="zh_female_qingchezizi_moon_bigtts", name="清澈梓梓"),
            Voice(voice_id="zh_female_qingxinnvsheng_mars_bigtts", name="清新女声"),
            Voice(voice_id="zh_female_qinqienvsheng_moon_bigtts", name="亲切女声"),
            Voice(voice_id="zh_female_roumeinvyou_emo_v2_mars_bigtts",
                  name="柔美女友（多情感）"),
            Voice(voice_id="zh_female_sajiaonvyou_moon_bigtts", name="柔美女友"),
            Voice(voice_id="zh_female_shaoergushi_mars_bigtts", name="少儿故事"),
            Voice(voice_id="zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
                  name="爽快思思（多情感）"),
            Voice(voice_id="zh_female_shuangkuaisisi_moon_bigtts", name="爽快思思/Skye"),
            Voice(voice_id="zh_female_sophie_conversation_wvae_bigtts", name="魅力苏菲"),
            Voice(voice_id="zh_female_tianmeitaozi_mars_bigtts", name="甜美桃子"),
            Voice(voice_id="zh_female_tianmeixiaoyuan_moon_bigtts", name="甜美小源"),
            Voice(voice_id="zh_female_tianmeiyueyue_moon_bigtts", name="甜美悦悦"),
            Voice(voice_id="zh_female_tianxinxiaomei_emo_v2_mars_bigtts",
                  name="甜心小美（多情感）"),
            Voice(voice_id="zh_female_tiexinnvsheng_mars_bigtts", name="贴心女声/Candy"),
            Voice(voice_id="zh_female_vv_mars_bigtts", name="Vivi"),
            Voice(voice_id="zh_female_wanqudashu_moon_bigtts", name="湾区大叔"),
            Voice(voice_id="zh_female_wanwanxiaohe_moon_bigtts", name="湾湾小何"),
            Voice(voice_id="zh_female_wenroushunv_mars_bigtts", name="温柔淑女"),
            Voice(voice_id="zh_female_wenrouxiaoya_moon_bigtts", name="温柔小雅"),
            Voice(voice_id="zh_female_wuzetian_mars_bigtts", name="武则天"),
            Voice(voice_id="zh_female_xinlingjitang_moon_bigtts", name="心灵鸡汤"),
            Voice(voice_id="zh_female_yangmi_mars_bigtts", name="林潇"),
            Voice(voice_id="zh_female_yingtaowanzi_mars_bigtts", name="樱桃丸子"),
            Voice(voice_id="zh_female_yingyujiaoyu_mars_bigtts", name="Tina老师"),
            Voice(voice_id="zh_female_yuanqinvyou_moon_bigtts", name="撒娇学妹"),
            Voice(voice_id="zh_female_yueyunv_mars_bigtts", name="粤语小溏"),
            Voice(voice_id="zh_female_zhixingnvsheng_mars_bigtts", name="知性女声"),
            Voice(voice_id="zh_male_M100_conversation_wvae_bigtts", name="悠悠君子"),
            Voice(voice_id="zh_male_aojiaobazong_emo_v2_mars_bigtts",
                  name="傲娇霸总（多情感）"),
            Voice(voice_id="zh_male_aojiaobazong_moon_bigtts", name="傲娇霸总"),
            Voice(voice_id="zh_male_baqiqingshu_mars_bigtts", name="霸气青叔"),
            Voice(voice_id="zh_male_beijingxiaoye_emo_v2_mars_bigtts",
                  name="北京小爷（多情感）"),
            Voice(voice_id="zh_male_beijingxiaoye_moon_bigtts", name="北京小爷"),
            Voice(voice_id="zh_male_changtianyi_mars_bigtts", name="悬疑解说"),
            Voice(voice_id="zh_male_chunhui_mars_bigtts", name="广告解说"),
            Voice(voice_id="zh_male_dongfanghaoran_moon_bigtts", name="东方浩然"),
            Voice(voice_id="zh_male_dongmanhaimian_mars_bigtts", name="亮嗓萌仔"),
            Voice(voice_id="zh_male_fanjuanqingnian_mars_bigtts", name="反卷青年"),
            Voice(voice_id="zh_male_guangxiyuanzhou_moon_bigtts", name="广西远舟"),
            Voice(voice_id="zh_male_guangzhoudege_emo_mars_bigtts",
                  name="广州德哥（多情感）"),
            Voice(voice_id="zh_male_guozhoudege_moon_bigtts", name="广州德哥"),
            Voice(voice_id="zh_male_haoyuxiaoge_moon_bigtts", name="浩宇小哥"),
            Voice(voice_id="zh_male_hupunan_mars_bigtts", name="沪普男"),
            Voice(voice_id="zh_male_jieshuonansheng_mars_bigtts",
                  name="磁性解说男声/Morgan"),
            Voice(voice_id="zh_male_jieshuoxiaoming_moon_bigtts", name="解说小明"),
            Voice(voice_id="zh_male_jingqiangkanye_emo_mars_bigtts",
                  name="京腔侃爷（多情感）"),
            Voice(voice_id="zh_male_jingqiangkanye_moon_bigtts",
                  name="京腔侃爷/Harmony"),
            Voice(voice_id="zh_male_junlangnanyou_emo_v2_mars_bigtts",
                  name="俊朗男友（多情感）"),
            Voice(voice_id="zh_male_lanxiaoyang_mars_bigtts", name="懒音绵宝"),
            Voice(voice_id="zh_male_lengkugege_emo_v2_mars_bigtts",
                  name="冷酷哥哥（多情感）"),
            Voice(voice_id="zh_male_linjiananhai_moon_bigtts", name="邻家男孩"),
            Voice(voice_id="zh_male_livelybro_mars_bigtts", name="开朗弟弟"),
            Voice(voice_id="zh_male_lubanqihao_mars_bigtts", name="鲁班七号"),
            Voice(voice_id="zh_male_naiqimengwa_mars_bigtts", name="奶气萌娃"),
            Voice(voice_id="zh_male_qingcang_mars_bigtts", name="擎苍"),
            Voice(voice_id="zh_male_qingshuangnanda_mars_bigtts", name="清爽男大"),
            Voice(voice_id="zh_male_qingyiyuxuan_mars_bigtts", name="阳光阿辰"),
            Voice(voice_id="zh_male_ruyaqingnian_mars_bigtts", name="儒雅青年"),
            Voice(voice_id="zh_male_ruyayichen_emo_v2_mars_bigtts",
                  name="儒雅男友（多情感）"),
            Voice(voice_id="zh_male_shaonianzixin_moon_bigtts", name="少年梓辛/Brayan"),
            Voice(voice_id="zh_male_shenyeboke_emo_v2_mars_bigtts", name="深夜播客"),
            Voice(voice_id="zh_male_shenyeboke_moon_bigtts", name="深夜播客"),
            Voice(voice_id="zh_male_silang_mars_bigtts", name="四郎"),
            Voice(voice_id="zh_male_sunwukong_mars_bigtts", name="猴哥"),
            Voice(voice_id="zh_male_tangseng_mars_bigtts", name="唐僧"),
            Voice(voice_id="zh_male_tiancaitongsheng_mars_bigtts", name="天才童声"),
            Voice(voice_id="zh_male_wennuanahu_moon_bigtts", name="温暖阿虎/Alvin"),
            Voice(voice_id="zh_male_wenrouxiaoge_mars_bigtts", name="温柔小哥"),
            Voice(voice_id="zh_male_xionger_mars_bigtts", name="熊二"),
            Voice(voice_id="zh_male_xudong_conversation_wvae_bigtts", name="快乐小东"),
            Voice(voice_id="zh_male_yangguangqingnian_emo_v2_mars_bigtts",
                  name="阳光青年（多情感）"),
            Voice(voice_id="zh_male_yangguangqingnian_mars_bigtts", name="活力小哥"),
            Voice(voice_id="zh_male_yangguangqingnian_moon_bigtts", name="阳光青年"),
            Voice(voice_id="zh_male_yourougongzi_emo_v2_mars_bigtts",
                  name="优柔公子（多情感）"),
            Voice(voice_id="zh_male_yuanboxiaoshu_moon_bigtts", name="渊博小叔"),
            Voice(voice_id="zh_male_yuzhouzixuan_moon_bigtts", name="豫州子轩"),
            Voice(voice_id="zh_male_zhoujielun_emo_v2_mars_bigtts", name="双节棍小哥"),
            Voice(voice_id="zh_male_zhuangzhou_mars_bigtts", name="庄周"),
            Voice(voice_id="zh_male_zhubajie_mars_bigtts", name="猪八戒"),
        ],
        "en-GB": [
            Voice(voice_id="en_female_anna_mars_bigtts", name="Anna"),
            Voice(voice_id="en_female_daisy_moon_bigtts", name="DelicateGirl"),
            Voice(voice_id="en_female_emily_mars_bigtts", name="Emily"),
            Voice(voice_id="en_female_nadia_tips_emo_v2_mars_bigtts", name="Nadia"),
            Voice(voice_id="en_female_onez_moon_bigtts", name="Onez"),
            Voice(voice_id="en_male_corey_emo_v2_mars_bigtts", name="Corey"),
            Voice(voice_id="en_male_dave_moon_bigtts", name="Dave"),
            Voice(voice_id="en_male_hades_moon_bigtts", name="Hades"),
            Voice(voice_id="en_male_smith_mars_bigtts", name="Smith"),
            Voice(voice_id="zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
                  name="爽快思思（多情感）"),
            Voice(voice_id="zh_female_yingyujiaoyu_mars_bigtts", name="Tina老师"),
            Voice(voice_id="zh_male_xudong_conversation_wvae_bigtts", name="Daniel"),
        ],
        "en-US": [
            Voice(voice_id="en_female_amanda_mars_bigtts", name="Amanda"),
            Voice(voice_id="en_female_candice_emo_v2_mars_bigtts", name="Candice"),
            Voice(voice_id="en_female_dacey_conversation_wvae_bigtts", name="Daisy"),
            Voice(voice_id="en_female_emotional_moon_bigtts",
                  name="PeacefulFemale"),
            Voice(voice_id="en_female_lauren_moon_bigtts", name="Lauren"),
            Voice(voice_id="en_female_nara_moon_bigtts", name="Nara"),
            Voice(voice_id="en_female_product_darcie_moon_bigtts",
                  name="FlirtyFemale"),
            Voice(voice_id="en_female_sarah_new_conversation_wvae_bigtts", name="Luna"),
            Voice(voice_id="en_female_skye_emo_v2_mars_bigtts", name="Serena"),
            Voice(voice_id="en_male_adam_mars_bigtts", name="Adam"),
            Voice(voice_id="en_male_bruce_moon_bigtts", name="Bruce"),
            Voice(voice_id="en_male_campaign_jamal_moon_bigtts",
                  name="EnergeticMaleII"),
            Voice(voice_id="en_male_charlie_conversation_wvae_bigtts", name="Owen"),
            Voice(voice_id="en_male_chris_moon_bigtts", name="GothamHero"),
            Voice(voice_id="en_male_glen_emo_v2_mars_bigtts", name="Glen"),
            Voice(voice_id="en_male_jackson_mars_bigtts", name="Jackson"),
            Voice(voice_id="en_male_sylus_emo_v2_mars_bigtts", name="Sylus"),
            Voice(voice_id="zh_female_cancan_mars_bigtts", name="灿灿/Shiny"),
            Voice(voice_id="zh_female_jitangmeimei_mars_bigtts", name="鸡汤妹妹/Hope"),
            Voice(voice_id="zh_female_mengyatou_mars_bigtts", name="萌丫头/Cutey"),
            Voice(voice_id="zh_female_shuangkuaisisi_moon_bigtts", name="爽快思思/Skye"),
            Voice(voice_id="zh_female_sophie_conversation_wvae_bigtts", name="Sophie"),
            Voice(voice_id="zh_female_tiexinnvsheng_mars_bigtts", name="贴心女声/Candy"),
            Voice(voice_id="zh_male_M100_conversation_wvae_bigtts", name="Lucas"),
            Voice(voice_id="zh_male_jieshuonansheng_mars_bigtts",
                  name="磁性解说男声/Morgan"),
            Voice(voice_id="zh_male_jingqiangkanye_moon_bigtts",
                  name="京腔侃爷/Harmony"),
            Voice(voice_id="zh_male_shaonianzixin_moon_bigtts", name="少年梓辛/Brayan"),
            Voice(voice_id="zh_male_wennuanahu_moon_bigtts", name="温暖阿虎/Alvin"),
        ],
        "es-ES": [
            Voice(voice_id="multi_female_maomao_conversation_wvae_bigtts", name="Diana"),
            Voice(voice_id="multi_female_shuangkuaisisi_moon_bigtts",
                  name="はるこ（晴子）/Esmeralda"),
            Voice(voice_id="multi_female_sophie_conversation_wvae_bigtts", name="Sofía"),
            Voice(voice_id="multi_male_M100_conversation_wvae_bigtts", name="Lucía"),
            Voice(voice_id="multi_male_jingqiangkanye_moon_bigtts",
                  name="かずね（和音）/JavierorÁlvaro"),
            Voice(voice_id="multi_male_wanqudashu_moon_bigtts",
                  name="ひろし（広志）/Roberto"),
            Voice(voice_id="multi_male_xudong_conversation_wvae_bigtts",
                  name="Daníel"),
        ],
        "ja-JP": [
            Voice(voice_id="multi_female_gaolengyujie_moon_bigtts", name="あけみ（朱美）"),
            Voice(voice_id="multi_female_maomao_conversation_wvae_bigtts", name="つき（月）"),
            Voice(voice_id="multi_female_shuangkuaisisi_moon_bigtts",
                  name="はるこ（晴子）/Esmeralda"),
            Voice(voice_id="multi_female_sophie_conversation_wvae_bigtts",
                  name="さとみ（智美）"),
            Voice(voice_id="multi_male_jingqiangkanye_moon_bigtts",
                  name="かずね（和音）/JavierorÁlvaro"),
            Voice(voice_id="multi_male_wanqudashu_moon_bigtts",
                  name="ひろし（広志）/Roberto"),
            Voice(voice_id="multi_male_xudong_conversation_wvae_bigtts",
                  name="まさお（正男）"),
            Voice(voice_id="multi_zh_male_youyoujunzi_moon_bigtts", name="ひかる（光）"),
        ],
    },
}
# VALID_VOICES_END
