"""Static configuration"""

from typing import Mapping

from homeassistant.components.tts import Voice

VALID_LANGUAGES: Mapping[str, list[str]] = {
    "volc.bigasr.sauc.duration": ["zh-CN", "en-US", "ja-JP", "id-ID", "es-MX", "pt-BR", "de-DE", "fr-FR", "ko-KR", "fil-PH", "ms-MY", "th-TH", "ar-SA", "it-IT", "bn-BD", "el-GR", "nl-NL", "ru-RU", "tr-TR", "vi-VN", "pl-PL", "ro-RO", "ne-NP", "uk-UA", "yue-CN"],
    "volc.bigasr.sauc.concurrent": ["zh-CN", "en-US", "ja-JP", "id-ID", "es-MX", "pt-BR", "de-DE", "fr-FR", "ko-KR", "fil-PH", "ms-MY", "th-TH", "ar-SA", "it-IT", "bn-BD", "el-GR", "nl-NL", "ru-RU", "tr-TR", "vi-VN", "pl-PL", "ro-RO", "ne-NP", "uk-UA", "yue-CN"],
    "volc.seedasr.sauc.duration": ["zh-CN", "en-US", "ja-JP", "id-ID", "es-MX", "pt-BR", "de-DE", "fr-FR", "ko-KR", "fil-PH", "ms-MY", "th-TH", "ar-SA", "it-IT", "bn-BD", "el-GR", "nl-NL", "ru-RU", "tr-TR", "vi-VN", "pl-PL", "ro-RO", "ne-NP", "uk-UA", "yue-CN"],
    "volc.seedasr.sauc.concurrent": ["zh-CN", "en-US", "ja-JP", "id-ID", "es-MX", "pt-BR", "de-DE", "fr-FR", "ko-KR", "fil-PH", "ms-MY", "th-TH", "ar-SA", "it-IT", "bn-BD", "el-GR", "nl-NL", "ru-RU", "tr-TR", "vi-VN", "pl-PL", "ro-RO", "ne-NP", "uk-UA", "yue-CN"]
}

DEFAULT_VOICES: Mapping[str, str] = {
    "seed-tts-2.0": "zh_female_vv_uranus_bigtts",
    "seed-tts-1.0": "zh_female_vv_mars_bigtts",
    "seed-tts-1.0-concurr": "zh_female_vv_mars_bigtts"
}

# Valid voices config
VALID_VOICES: Mapping[str, Mapping[str, list[Voice]]] = {
    "seed-tts-2.0": {
        "zh-CN": [
            Voice(voice_id="zh_female_vv_uranus_bigtts", name="Vivi 2.0"),
            Voice(voice_id="zh_female_xiaohe_uranus_bigtts", name="小何 2.0"),
            Voice(voice_id="zh_male_m191_uranus_bigtts", name="云舟 2.0"),
            Voice(voice_id="zh_male_taocheng_uranus_bigtts", name="小天 2.0"),
            Voice(voice_id="zh_male_liufei_uranus_bigtts", name="刘飞 2.0"),
            Voice(voice_id="zh_male_sophie_uranus_bigtts", name="魅力苏菲 2.0"),
            Voice(
                voice_id="zh_female_qingxinnvsheng_uranus_bigtts",
                name="清新女声 2.0"),
            Voice(voice_id="zh_female_cancan_uranus_bigtts", name="知性灿灿 2.0"),
            Voice(
                voice_id="zh_female_sajiaoxuemei_uranus_bigtts",
                name="撒娇学妹 2.0"),
            Voice(voice_id="zh_female_tianmeixiaoyuan_uranus_bigtts",
                  name="甜美小源 2.0"),
            Voice(
                voice_id="zh_female_tianmeitaozi_uranus_bigtts",
                name="甜美桃子 2.0"),
            Voice(
                voice_id="zh_female_shuangkuaisisi_uranus_bigtts",
                name="爽快思思 2.0"),
            Voice(voice_id="zh_female_peiqi_uranus_bigtts", name="佩奇猪 2.0"),
            Voice(
                voice_id="zh_female_linjianvhai_uranus_bigtts",
                name="邻家女孩 2.0"),
            Voice(voice_id="zh_male_shaonianzixin_uranus_bigtts",
                  name="少年梓辛/Brayan 2.0"),
            Voice(voice_id="zh_male_sunwukong_uranus_bigtts", name="猴哥 2.0"),
            Voice(voice_id="zh_female_yingyujiaoxue_uranus_bigtts",
                  name="Tina老师 2.0"),
            Voice(
                voice_id="zh_female_kefunvsheng_uranus_bigtts",
                name="暖阳女声 2.0"),
            Voice(voice_id="zh_female_xiaoxue_uranus_bigtts", name="儿童绘本 2.0"),
            Voice(voice_id="zh_male_dayi_uranus_bigtts", name="大壹 2.0"),
            Voice(
                voice_id="zh_female_mizai_uranus_bigtts",
                name="黑猫侦探社咪仔 2.0"),
            Voice(voice_id="zh_female_jitangnv_uranus_bigtts", name="鸡汤女 2.0"),
            Voice(
                voice_id="zh_female_meilinvyou_uranus_bigtts",
                name="魅力女友 2.0"),
            Voice(
                voice_id="zh_female_liuchangnv_uranus_bigtts",
                name="流畅女声 2.0"),
            Voice(voice_id="zh_male_ruyayichen_uranus_bigtts", name="儒雅逸辰 2.0"),
            Voice(voice_id="saturn_zh_female_keainvsheng_tob", name="可爱女生"),
            Voice(voice_id="saturn_zh_female_tiaopigongzhu_tob", name="调皮公主"),
            Voice(voice_id="saturn_zh_male_shuanglangshaonian_tob", name="爽朗少年"),
            Voice(voice_id="saturn_zh_male_tiancaitongzhuo_tob", name="天才同桌"),
            Voice(voice_id="saturn_zh_female_cancan_tob", name="知性灿灿"),
            Voice(
                voice_id="saturn_zh_female_qingyingduoduo_cs_tob",
                name="轻盈朵朵 2.0"),
            Voice(
                voice_id="saturn_zh_female_wenwanshanshan_cs_tob",
                name="温婉珊珊 2.0"),
            Voice(
                voice_id="saturn_zh_female_reqingaina_cs_tob",
                name="热情艾娜 2.0")
        ],
        "en-US": [
            Voice(voice_id="en_male_tim_uranus_bigtts", name="Tim"),
            Voice(voice_id="en_female_dacey_uranus_bigtts", name="Dacey"),
            Voice(voice_id="en_female_stokie_uranus_bigtts", name="Stokie")
        ],
        "en-GB": [
            Voice(voice_id="zh_female_yingyujiaoxue_uranus_bigtts",
                  name="Tina老师 2.0")
        ],
        "ja-JP": [
            Voice(voice_id="zh_female_vv_uranus_bigtts", name="Vivi 2.0")
        ],
        "id-ID": [
            Voice(voice_id="zh_female_vv_uranus_bigtts", name="Vivi 2.0")
        ],
        "es-MX": [
            Voice(voice_id="zh_female_vv_uranus_bigtts", name="Vivi 2.0")
        ]
    },
    "seed-tts-1.0": {
        "zh-CN": [
            Voice(voice_id="zh_male_lengkugege_emo_v2_mars_bigtts",
                  name="冷酷哥哥（多情感）"),
            Voice(voice_id="zh_female_tianxinxiaomei_emo_v2_mars_bigtts",
                  name="甜心小美（多情感）"),
            Voice(voice_id="zh_female_gaolengyujie_emo_v2_mars_bigtts",
                  name="高冷御姐（多情感）"),
            Voice(voice_id="zh_male_aojiaobazong_emo_v2_mars_bigtts",
                  name="傲娇霸总（多情感）"),
            Voice(voice_id="zh_male_guangzhoudege_emo_mars_bigtts",
                  name="广州德哥（多情感）"),
            Voice(voice_id="zh_male_jingqiangkanye_emo_mars_bigtts",
                  name="京腔侃爷（多情感）"),
            Voice(voice_id="zh_female_linjuayi_emo_v2_mars_bigtts",
                  name="邻居阿姨（多情感）"),
            Voice(voice_id="zh_male_yourougongzi_emo_v2_mars_bigtts",
                  name="优柔公子（多情感）"),
            Voice(voice_id="zh_male_ruyayichen_emo_v2_mars_bigtts",
                  name="儒雅男友（多情感）"),
            Voice(voice_id="zh_male_junlangnanyou_emo_v2_mars_bigtts",
                  name="俊朗男友（多情感）"),
            Voice(voice_id="zh_male_beijingxiaoye_emo_v2_mars_bigtts",
                  name="北京小爷（多情感）"),
            Voice(voice_id="zh_female_roumeinvyou_emo_v2_mars_bigtts",
                  name="柔美女友（多情感）"),
            Voice(voice_id="zh_male_yangguangqingnian_emo_v2_mars_bigtts",
                  name="阳光青年（多情感）"),
            Voice(voice_id="zh_female_meilinvyou_emo_v2_mars_bigtts",
                  name="魅力女友（多情感）"),
            Voice(voice_id="zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
                  name="爽快思思（多情感）"),
            Voice(voice_id="中文", name="zh_male_shenyeboke_emo_v2_mars_bigtts"),
            Voice(voice_id="zh_female_yingyujiaoyu_mars_bigtts", name="Tina老师"),
            Voice(
                voice_id="ICL_zh_female_wenrounvshen_239eff5e8ffa_tob",
                name="温柔女神"),
            Voice(voice_id="zh_female_vv_mars_bigtts", name="Vivi"),
            Voice(voice_id="zh_female_qinqienvsheng_moon_bigtts", name="亲切女声"),
            Voice(voice_id="ICL_zh_male_shenmi_v1_tob", name="机灵小伙"),
            Voice(voice_id="ICL_zh_female_wuxi_tob", name="元气甜妹"),
            Voice(voice_id="ICL_zh_female_wenyinvsheng_v1_tob", name="知心姐姐"),
            Voice(voice_id="zh_male_qingyiyuxuan_mars_bigtts", name="阳光阿辰"),
            Voice(
                voice_id="zh_male_xudong_conversation_wvae_bigtts",
                name="快乐小东"),
            Voice(voice_id="ICL_zh_male_lengkugege_v1_tob", name="冷酷哥哥"),
            Voice(voice_id="ICL_zh_female_feicui_v1_tob", name="纯澈女生"),
            Voice(voice_id="ICL_zh_female_yuxin_v1_tob", name="初恋女友"),
            Voice(voice_id="ICL_zh_female_xnx_tob", name="贴心闺蜜"),
            Voice(voice_id="ICL_zh_female_yry_tob", name="温柔白月光"),
            Voice(voice_id="ICL_zh_male_BV705_streaming_cs_tob", name="炀炀"),
            Voice(
                voice_id="zh_female_sophie_conversation_wvae_bigtts",
                name="魅力苏菲"),
            Voice(voice_id="ICL_zh_female_yilin_tob", name="贴心妹妹"),
            Voice(voice_id="zh_female_tianmeitaozi_mars_bigtts", name="甜美桃子"),
            Voice(voice_id="zh_female_qingxinnvsheng_mars_bigtts", name="清新女声"),
            Voice(voice_id="zh_female_zhixingnvsheng_mars_bigtts", name="知性女声"),
            Voice(voice_id="zh_male_qingshuangnanda_mars_bigtts", name="清爽男大"),
            Voice(voice_id="zh_female_linjianvhai_moon_bigtts", name="邻家女孩"),
            Voice(voice_id="zh_male_yuanboxiaoshu_moon_bigtts", name="渊博小叔"),
            Voice(voice_id="zh_male_yangguangqingnian_moon_bigtts", name="阳光青年"),
            Voice(voice_id="zh_female_tianmeixiaoyuan_moon_bigtts", name="甜美小源"),
            Voice(voice_id="zh_female_qingchezizi_moon_bigtts", name="清澈梓梓"),
            Voice(voice_id="zh_male_jieshuoxiaoming_moon_bigtts", name="解说小明"),
            Voice(voice_id="zh_female_kailangjiejie_moon_bigtts", name="开朗姐姐"),
            Voice(voice_id="zh_male_linjiananhai_moon_bigtts", name="邻家男孩"),
            Voice(voice_id="zh_female_tianmeiyueyue_moon_bigtts", name="甜美悦悦"),
            Voice(voice_id="zh_female_xinlingjitang_moon_bigtts", name="心灵鸡汤"),
            Voice(voice_id="ICL_zh_female_zhixingwenwan_tob", name="知性温婉"),
            Voice(voice_id="ICL_zh_male_nuanxintitie_tob", name="暖心体贴"),
            Voice(voice_id="ICL_zh_male_kailangqingkuai_tob", name="开朗轻快"),
            Voice(voice_id="ICL_zh_male_huoposhuanglang_tob", name="活泼爽朗"),
            Voice(voice_id="ICL_zh_male_shuaizhenxiaohuo_tob", name="率真小伙"),
            Voice(voice_id="zh_male_wenrouxiaoge_mars_bigtts", name="温柔小哥"),
            Voice(voice_id="zh_female_cancan_mars_bigtts", name="灿灿/Shiny"),
            Voice(
                voice_id="zh_female_shuangkuaisisi_moon_bigtts",
                name="爽快思思/Skye"),
            Voice(
                voice_id="zh_male_wennuanahu_moon_bigtts",
                name="温暖阿虎/Alvin"),
            Voice(
                voice_id="zh_male_shaonianzixin_moon_bigtts",
                name="少年梓辛/Brayan"),
            Voice(voice_id="ICL_zh_female_wenrouwenya_tob", name="温柔文雅"),
            Voice(voice_id="仅中文豆包", name="zh_male_hupunan_mars_bigtts"),
            Voice(voice_id="zh_male_lubanqihao_mars_bigtts", name="鲁班七号"),
            Voice(voice_id="zh_female_yangmi_mars_bigtts", name="林潇"),
            Voice(voice_id="zh_female_linzhiling_mars_bigtts", name="玲玲姐姐"),
            Voice(voice_id="zh_female_jiyejizi2_mars_bigtts", name="春日部姐姐"),
            Voice(voice_id="zh_male_tangseng_mars_bigtts", name="唐僧"),
            Voice(voice_id="zh_male_zhuangzhou_mars_bigtts", name="庄周"),
            Voice(voice_id="zh_male_zhubajie_mars_bigtts", name="猪八戒"),
            Voice(voice_id="zh_female_ganmaodianyin_mars_bigtts", name="感冒电音姐姐"),
            Voice(voice_id="zh_female_naying_mars_bigtts", name="直率英子"),
            Voice(voice_id="zh_female_leidian_mars_bigtts", name="女雷神"),
            Voice(voice_id="zh_female_yueyunv_mars_bigtts", name="粤语小溏"),
            Voice(voice_id="zh_male_yuzhouzixuan_moon_bigtts", name="豫州子轩"),
            Voice(voice_id="zh_female_daimengchuanmei_moon_bigtts", name="呆萌川妹"),
            Voice(voice_id="zh_male_guangxiyuanzhou_moon_bigtts", name="广西远舟"),
            Voice(
                voice_id="zh_male_zhoujielun_emo_v2_mars_bigtts",
                name="双节棍小哥"),
            Voice(voice_id="zh_female_wanwanxiaohe_moon_bigtts", name="湾湾小何"),
            Voice(voice_id="zh_female_wanqudashu_moon_bigtts", name="湾区大叔"),
            Voice(voice_id="zh_male_guozhoudege_moon_bigtts", name="广州德哥"),
            Voice(voice_id="zh_male_haoyuxiaoge_moon_bigtts", name="浩宇小哥"),
            Voice(voice_id="zh_male_beijingxiaoye_moon_bigtts", name="北京小爷"),
            Voice(voice_id="zh_male_jingqiangkanye_moon_bigtts",
                  name="京腔侃爷/Harmony"),
            Voice(voice_id="zh_female_meituojieer_moon_bigtts", name="妹坨洁儿"),
            Voice(
                voice_id="ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob",
                name="纯真少女"),
            Voice(
                voice_id="ICL_zh_male_xiaonaigou_edf58cf28b8b_tob",
                name="奶气小生"),
            Voice(
                voice_id="ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob", name="精灵向导"),
            Voice(
                voice_id="ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob",
                name="闷油瓶小哥"),
            Voice(
                voice_id="ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob",
                name="黯刃秦主"),
            Voice(voice_id="ICL_zh_male_badaozongcai_v1_tob", name="霸道总裁"),
            Voice(voice_id="ICL_zh_female_ganli_v1_tob", name="妩媚可人"),
            Voice(voice_id="ICL_zh_female_xiangliangya_v1_tob", name="邪魅御姐"),
            Voice(voice_id="ICL_zh_male_ms_tob", name="嚣张小哥"),
            Voice(voice_id="ICL_zh_male_you_tob", name="油腻大叔"),
            Voice(voice_id="ICL_zh_male_guaogongzi_v1_tob", name="孤傲公子"),
            Voice(voice_id="ICL_zh_male_huzi_v1_tob", name="胡子叔叔"),
            Voice(voice_id="ICL_zh_female_luoqing_v1_tob", name="性感魅惑"),
            Voice(voice_id="ICL_zh_male_bingruogongzi_tob", name="病弱公子"),
            Voice(voice_id="ICL_zh_female_bingjiao3_tob", name="邪魅女王"),
            Voice(voice_id="ICL_zh_male_aomanqingnian_tob", name="傲慢青年"),
            Voice(voice_id="ICL_zh_male_cujingnansheng_tob", name="醋精男生"),
            Voice(voice_id="ICL_zh_male_shuanglangshaonian_tob", name="爽朗少年"),
            Voice(voice_id="ICL_zh_male_sajiaonanyou_tob", name="撒娇男友"),
            Voice(voice_id="ICL_zh_male_wenrounanyou_tob", name="温柔男友"),
            Voice(voice_id="ICL_zh_male_wenshunshaonian_tob", name="温顺少年"),
            Voice(voice_id="ICL_zh_male_naigounanyou_tob", name="粘人男友"),
            Voice(voice_id="ICL_zh_male_sajiaonansheng_tob", name="撒娇男生"),
            Voice(voice_id="ICL_zh_male_huoponanyou_tob", name="活泼男友"),
            Voice(voice_id="ICL_zh_male_tianxinanyou_tob", name="甜系男友"),
            Voice(voice_id="ICL_zh_male_huoliqingnian_tob", name="活力青年"),
            Voice(voice_id="ICL_zh_male_kailangqingnian_tob", name="开朗青年"),
            Voice(voice_id="ICL_zh_male_lengmoxiongzhang_tob", name="冷漠兄长"),
            Voice(voice_id="ICL_zh_male_tiancaitongzhuo_tob", name="天才同桌"),
            Voice(voice_id="ICL_zh_male_pianpiangongzi_tob", name="翩翩公子"),
            Voice(voice_id="ICL_zh_male_mengdongqingnian_tob", name="懵懂青年"),
            Voice(voice_id="ICL_zh_male_lenglianxiongzhang_tob", name="冷脸兄长"),
            Voice(voice_id="ICL_zh_male_bingjiaoshaonian_tob", name="病娇少年"),
            Voice(voice_id="ICL_zh_male_bingjiaonanyou_tob", name="病娇男友"),
            Voice(voice_id="ICL_zh_male_bingruoshaonian_tob", name="病弱少年"),
            Voice(voice_id="ICL_zh_male_yiqishaonian_tob", name="意气少年"),
            Voice(voice_id="ICL_zh_male_ganjingshaonian_tob", name="干净少年"),
            Voice(voice_id="ICL_zh_male_lengmonanyou_tob", name="冷漠男友"),
            Voice(voice_id="ICL_zh_male_jingyingqingnian_tob", name="精英青年"),
            Voice(voice_id="ICL_zh_male_rexueshaonian_tob", name="热血少年"),
            Voice(voice_id="ICL_zh_male_qingshuangshaonian_tob", name="清爽少年"),
            Voice(voice_id="ICL_zh_male_zhongerqingnian_tob", name="中二青年"),
            Voice(voice_id="ICL_zh_male_lingyunqingnian_tob", name="凌云青年"),
            Voice(voice_id="ICL_zh_male_zifuqingnian_tob", name="自负青年"),
            Voice(voice_id="ICL_zh_male_bujiqingnian_tob", name="不羁青年"),
            Voice(voice_id="ICL_zh_male_ruyajunzi_tob", name="儒雅君子"),
            Voice(voice_id="ICL_zh_male_diyinchenyu_tob", name="低音沉郁"),
            Voice(voice_id="ICL_zh_male_lenglianxueba_tob", name="冷脸学霸"),
            Voice(voice_id="ICL_zh_male_ruyazongcai_tob", name="儒雅总裁"),
            Voice(voice_id="ICL_zh_male_shenchenzongcai_tob", name="深沉总裁"),
            Voice(voice_id="ICL_zh_male_xiaohouye_tob", name="小侯爷"),
            Voice(voice_id="ICL_zh_male_gugaogongzi_tob", name="孤高公子"),
            Voice(voice_id="ICL_zh_male_zhangjianjunzi_tob", name="仗剑君子"),
            Voice(voice_id="ICL_zh_male_wenrunxuezhe_tob", name="温润学者"),
            Voice(voice_id="ICL_zh_male_qinqieqingnian_tob", name="亲切青年"),
            Voice(voice_id="ICL_zh_male_wenrouxuezhang_tob", name="温柔学长"),
            Voice(voice_id="ICL_zh_male_gaolengzongcai_tob", name="高冷总裁"),
            Voice(voice_id="ICL_zh_male_lengjungaozhi_tob", name="冷峻高智"),
            Voice(voice_id="ICL_zh_male_chanruoshaoye_tob", name="孱弱少爷"),
            Voice(voice_id="ICL_zh_male_zixinqingnian_tob", name="自信青年"),
            Voice(voice_id="ICL_zh_male_qingseqingnian_tob", name="青涩青年"),
            Voice(voice_id="ICL_zh_male_xuebatongzhuo_tob", name="学霸同桌"),
            Voice(voice_id="ICL_zh_male_lengaozongcai_tob", name="冷傲总裁"),
            Voice(voice_id="ICL_zh_male_yuanqishaonian_tob", name="元气少年"),
            Voice(voice_id="ICL_zh_male_satuoqingnian_tob", name="洒脱青年"),
            Voice(voice_id="ICL_zh_male_zhishuaiqingnian_tob", name="直率青年"),
            Voice(voice_id="ICL_zh_male_siwenqingnian_tob", name="斯文青年"),
            Voice(voice_id="ICL_zh_male_junyigongzi_tob", name="俊逸公子"),
            Voice(voice_id="ICL_zh_male_zhangjianxiake_tob", name="仗剑侠客"),
            Voice(voice_id="ICL_zh_male_jijiaozhineng_tob", name="机甲智能"),
            Voice(voice_id="zh_male_naiqimengwa_mars_bigtts", name="奶气萌娃"),
            Voice(voice_id="zh_female_popo_mars_bigtts", name="婆婆"),
            Voice(voice_id="zh_female_gaolengyujie_moon_bigtts", name="高冷御姐"),
            Voice(voice_id="zh_male_aojiaobazong_moon_bigtts", name="傲娇霸总"),
            Voice(voice_id="zh_female_meilinvyou_moon_bigtts", name="魅力女友"),
            Voice(voice_id="zh_male_shenyeboke_moon_bigtts", name="深夜播客"),
            Voice(voice_id="zh_female_sajiaonvyou_moon_bigtts", name="柔美女友"),
            Voice(voice_id="zh_female_yuanqinvyou_moon_bigtts", name="撒娇学妹"),
            Voice(voice_id="ICL_zh_female_bingruoshaonv_tob", name="病弱少女"),
            Voice(voice_id="ICL_zh_female_huoponvhai_tob", name="活泼女孩"),
            Voice(voice_id="zh_male_dongfanghaoran_moon_bigtts", name="东方浩然"),
            Voice(voice_id="ICL_zh_male_lvchaxiaoge_tob", name="绿茶小哥"),
            Voice(voice_id="ICL_zh_female_jiaoruoluoli_tob", name="娇弱萝莉"),
            Voice(voice_id="ICL_zh_male_lengdanshuli_tob", name="冷淡疏离"),
            Voice(voice_id="ICL_zh_male_hanhoudunshi_tob", name="憨厚敦实"),
            Voice(voice_id="ICL_zh_female_huopodiaoman_tob", name="活泼刁蛮"),
            Voice(voice_id="ICL_zh_male_guzhibingjiao_tob", name="固执病娇"),
            Voice(voice_id="ICL_zh_male_sajiaonianren_tob", name="撒娇粘人"),
            Voice(voice_id="ICL_zh_female_aomanjiaosheng_tob", name="傲慢娇声"),
            Voice(voice_id="ICL_zh_male_xiaosasuixing_tob", name="潇洒随性"),
            Voice(voice_id="ICL_zh_male_guiyishenmi_tob", name="诡异神秘"),
            Voice(voice_id="ICL_zh_male_ruyacaijun_tob", name="儒雅才俊"),
            Voice(voice_id="ICL_zh_male_zhengzhiqingnian_tob", name="正直青年"),
            Voice(voice_id="ICL_zh_female_jiaohannvwang_tob", name="娇憨女王"),
            Voice(voice_id="ICL_zh_female_bingjiaomengmei_tob", name="病娇萌妹"),
            Voice(voice_id="ICL_zh_male_qingsenaigou_tob", name="青涩小生"),
            Voice(voice_id="ICL_zh_male_chunzhenxuedi_tob", name="纯真学弟"),
            Voice(voice_id="ICL_zh_male_youroubangzhu_tob", name="优柔帮主"),
            Voice(voice_id="ICL_zh_male_yourougongzi_tob", name="优柔公子"),
            Voice(voice_id="ICL_zh_female_tiaopigongzhu_tob", name="调皮公主"),
            Voice(voice_id="ICL_zh_male_tiexinnanyou_tob", name="贴心男友"),
            Voice(voice_id="ICL_zh_male_shaonianjiangjun_tob", name="少年将军"),
            Voice(voice_id="ICL_zh_male_bingjiaogege_tob", name="病娇哥哥"),
            Voice(voice_id="ICL_zh_male_xuebanantongzhuo_tob", name="学霸男同桌"),
            Voice(voice_id="ICL_zh_male_youmoshushu_tob", name="幽默叔叔"),
            Voice(voice_id="ICL_zh_female_jiaxiaozi_tob", name="假小子"),
            Voice(voice_id="ICL_zh_male_wenrounantongzhuo_tob", name="温柔男同桌"),
            Voice(voice_id="ICL_zh_male_youmodaye_tob", name="幽默大爷"),
            Voice(voice_id="ICL_zh_male_asmryexiu_tob", name="枕边低语"),
            Voice(voice_id="ICL_zh_male_shenmifashi_tob", name="神秘法师"),
            Voice(voice_id="zh_female_jiaochuan_mars_bigtts", name="娇喘女声"),
            Voice(voice_id="zh_male_livelybro_mars_bigtts", name="开朗弟弟"),
            Voice(voice_id="zh_female_flattery_mars_bigtts", name="谄媚女声"),
            Voice(voice_id="ICL_zh_male_lengjunshangsi_tob", name="冷峻上司"),
            Voice(voice_id="ICL_zh_male_xiaoge_v1_tob", name="寡言小哥"),
            Voice(voice_id="ICL_zh_male_renyuwangzi_v1_tob", name="清朗温润"),
            Voice(voice_id="ICL_zh_male_xiaosha_v1_tob", name="潇洒随性"),
            Voice(voice_id="ICL_zh_male_liyisheng_v1_tob", name="清冷矜贵"),
            Voice(voice_id="ICL_zh_male_qinglen_v1_tob", name="沉稳优雅"),
            Voice(voice_id="ICL_zh_male_chongqingzhanzhan_v1_tob", name="清逸苏感"),
            Voice(voice_id="ICL_zh_male_xingjiwangzi_v1_tob", name="温柔内敛"),
            Voice(voice_id="ICL_zh_male_sigeshiye_v1_tob", name="低沉缱绻"),
            Voice(voice_id="ICL_zh_male_lanyingcaohunshi_v1_tob", name="蓝银草魂师"),
            Voice(voice_id="ICL_zh_female_liumengdie_v1_tob", name="清冷高雅"),
            Voice(voice_id="ICL_zh_female_linxueying_v1_tob", name="甜美娇俏"),
            Voice(voice_id="ICL_zh_female_rouguhunshi_v1_tob", name="柔骨魂师"),
            Voice(voice_id="ICL_zh_female_tianmei_v1_tob", name="甜美活泼"),
            Voice(voice_id="ICL_zh_female_chengshu_v1_tob", name="成熟温柔"),
            Voice(voice_id="ICL_zh_female_xnx_v1_tob", name="贴心闺蜜"),
            Voice(voice_id="ICL_zh_female_yry_v1_tob", name="温柔白月光"),
            Voice(voice_id="zh_male_bv139_audiobook_ummv3_bigtts", name="高冷沉稳"),
            Voice(voice_id="ICL_zh_male_cujingnanyou_tob", name="醋精男友"),
            Voice(voice_id="ICL_zh_male_fengfashaonian_tob", name="风发少年"),
            Voice(voice_id="ICL_zh_male_cixingnansang_tob", name="磁性男嗓"),
            Voice(voice_id="ICL_zh_male_chengshuzongcai_tob", name="成熟总裁"),
            Voice(voice_id="ICL_zh_male_aojiaojingying_tob", name="傲娇精英"),
            Voice(voice_id="ICL_zh_male_aojiaogongzi_tob", name="傲娇公子"),
            Voice(voice_id="ICL_zh_male_badaoshaoye_tob", name="霸道少爷"),
            Voice(voice_id="ICL_zh_male_fuheigongzi_tob", name="腹黑公子"),
            Voice(voice_id="ICL_zh_female_nuanxinxuejie_tob", name="暖心学姐"),
            Voice(voice_id="ICL_zh_female_keainvsheng_tob", name="可爱女生"),
            Voice(voice_id="ICL_zh_female_chengshujiejie_tob", name="成熟姐姐"),
            Voice(voice_id="ICL_zh_female_bingjiaojiejie_tob", name="病娇姐姐"),
            Voice(voice_id="ICL_zh_female_wumeiyujie_tob", name="妩媚御姐"),
            Voice(voice_id="ICL_zh_female_aojiaonvyou_tob", name="傲娇女友"),
            Voice(voice_id="ICL_zh_female_tiexinnvyou_tob", name="贴心女友"),
            Voice(voice_id="ICL_zh_female_xingganyujie_tob", name="性感御姐"),
            Voice(voice_id="ICL_zh_male_bingjiaodidi_tob", name="病娇弟弟"),
            Voice(voice_id="ICL_zh_male_aomanshaoye_tob", name="傲慢少爷"),
            Voice(voice_id="ICL_zh_male_aiqilingren_tob", name="傲气凌人"),
            Voice(voice_id="ICL_zh_male_bingjiaobailian_tob", name="病娇白莲"),
            Voice(
                voice_id="zh_male_M100_conversation_wvae_bigtts",
                name="Lucas"),
            Voice(
                voice_id="zh_female_sophie_conversation_wvae_bigtts",
                name="Sophie"),
            Voice(
                voice_id="zh_male_xudong_conversation_wvae_bigtts",
                name="Daniel"),
            Voice(
                voice_id="multi_zh_male_youyoujunzi_moon_bigtts",
                name="ひかる（光）"),
            Voice(voice_id="ICL_zh_female_lixingyuanzi_cs_tob", name="理性圆子"),
            Voice(voice_id="ICL_zh_female_qingtiantaotao_cs_tob", name="清甜桃桃"),
            Voice(voice_id="ICL_zh_female_qingxixiaoxue_cs_tob", name="清晰小雪"),
            Voice(voice_id="ICL_zh_female_qingtianmeimei_cs_tob", name="清甜莓莓"),
            Voice(voice_id="ICL_zh_female_kailangtingting_cs_tob", name="开朗婷婷"),
            Voice(voice_id="ICL_zh_male_qingxinmumu_cs_tob", name="清新沐沐"),
            Voice(voice_id="ICL_zh_male_shuanglangxiaoyang_cs_tob", name="爽朗小阳"),
            Voice(voice_id="ICL_zh_male_qingxinbobo_cs_tob", name="清新波波"),
            Voice(voice_id="ICL_zh_female_wenwanshanshan_cs_tob", name="温婉珊珊"),
            Voice(voice_id="ICL_zh_female_tianmeixiaoyu_cs_tob", name="甜美小雨"),
            Voice(voice_id="ICL_zh_female_reqingaina_cs_tob", name="热情艾娜"),
            Voice(voice_id="ICL_zh_female_tianmeixiaoju_cs_tob", name="甜美小橘"),
            Voice(voice_id="ICL_zh_male_chenwenmingzai_cs_tob", name="沉稳明仔"),
            Voice(voice_id="ICL_zh_male_qinqiexiaozhuo_cs_tob", name="亲切小卓"),
            Voice(voice_id="ICL_zh_female_lingdongxinxin_cs_tob", name="灵动欣欣"),
            Voice(voice_id="ICL_zh_female_guaiqiaokeer_cs_tob", name="乖巧可儿"),
            Voice(voice_id="ICL_zh_female_nuanxinqianqian_cs_tob", name="暖心茜茜"),
            Voice(voice_id="ICL_zh_female_ruanmengtuanzi_cs_tob", name="软萌团子"),
            Voice(voice_id="ICL_zh_male_yangguangyangyang_cs_tob", name="阳光洋洋"),
            Voice(voice_id="ICL_zh_female_ruanmengtangtang_cs_tob", name="软萌糖糖"),
            Voice(voice_id="ICL_zh_female_xiuliqianqian_cs_tob", name="秀丽倩倩"),
            Voice(voice_id="ICL_zh_female_kaixinxiaohong_cs_tob", name="开心小鸿"),
            Voice(voice_id="ICL_zh_female_qingyingduoduo_cs_tob", name="轻盈朵朵"),
            Voice(voice_id="zh_female_kefunvsheng_mars_bigtts", name="暖阳女声"),
            Voice(voice_id="zh_male_M100_conversation_wvae_bigtts", name="悠悠君子"),
            Voice(
                voice_id="zh_female_maomao_conversation_wvae_bigtts",
                name="文静毛毛"),
            Voice(voice_id="ICL_zh_female_qiuling_v1_tob", name="倾心少女"),
            Voice(voice_id="ICL_zh_male_buyan_v1_tob", name="醇厚低音"),
            Voice(voice_id="ICL_zh_male_BV144_paoxiaoge_v1_tob", name="咆哮小哥"),
            Voice(voice_id="ICL_zh_female_heainainai_tob", name="和蔼奶奶"),
            Voice(voice_id="ICL_zh_female_linjuayi_tob", name="邻居阿姨"),
            Voice(voice_id="zh_female_wenrouxiaoya_moon_bigtts", name="温柔小雅"),
            Voice(voice_id="zh_male_tiancaitongsheng_mars_bigtts", name="天才童声"),
            Voice(voice_id="zh_male_sunwukong_mars_bigtts", name="猴哥"),
            Voice(voice_id="zh_male_xionger_mars_bigtts", name="熊二"),
            Voice(voice_id="zh_female_peiqi_mars_bigtts", name="佩奇猪"),
            Voice(voice_id="zh_female_wuzetian_mars_bigtts", name="武则天"),
            Voice(voice_id="zh_female_gujie_mars_bigtts", name="顾姐"),
            Voice(voice_id="zh_female_yingtaowanzi_mars_bigtts", name="樱桃丸子"),
            Voice(voice_id="zh_male_chunhui_mars_bigtts", name="广告解说"),
            Voice(voice_id="zh_female_shaoergushi_mars_bigtts", name="少儿故事"),
            Voice(voice_id="zh_male_silang_mars_bigtts", name="四郎"),
            Voice(voice_id="zh_female_qiaopinvsheng_mars_bigtts", name="俏皮女声"),
            Voice(voice_id="zh_male_lanxiaoyang_mars_bigtts", name="懒音绵宝"),
            Voice(voice_id="zh_male_dongmanhaimian_mars_bigtts", name="亮嗓萌仔"),
            Voice(voice_id="zh_male_jieshuonansheng_mars_bigtts",
                  name="磁性解说男声/Morgan"),
            Voice(
                voice_id="zh_female_jitangmeimei_mars_bigtts",
                name="鸡汤妹妹/Hope"),
            Voice(
                voice_id="zh_female_tiexinnvsheng_mars_bigtts",
                name="贴心女声/Candy"),
            Voice(
                voice_id="zh_female_mengyatou_mars_bigtts",
                name="萌丫头/Cutey"),
            Voice(
                voice_id="ICL_zh_male_neiliancaijun_e991be511569_tob",
                name="内敛才俊"),
            Voice(voice_id="ICL_zh_male_yangyang_v1_tob", name="温暖少年"),
            Voice(voice_id="ICL_zh_male_flc_v1_tob", name="儒雅公子"),
            Voice(voice_id="zh_male_changtianyi_mars_bigtts", name="悬疑解说"),
            Voice(voice_id="zh_male_ruyaqingnian_mars_bigtts", name="儒雅青年"),
            Voice(voice_id="zh_male_baqiqingshu_mars_bigtts", name="霸气青叔"),
            Voice(voice_id="zh_male_qingcang_mars_bigtts", name="擎苍"),
            Voice(voice_id="zh_male_yangguangqingnian_mars_bigtts", name="活力小哥"),
            Voice(voice_id="zh_female_gufengshaoyu_mars_bigtts", name="古风少御"),
            Voice(voice_id="zh_female_wenroushunv_mars_bigtts", name="温柔淑女"),
            Voice(voice_id="zh_male_fanjuanqingnian_mars_bigtts", name="反卷青年")
        ],
        "en-US": [
            Voice(
                voice_id="en_female_candice_emo_v2_mars_bigtts",
                name="Candice"),
            Voice(voice_id="en_female_skye_emo_v2_mars_bigtts", name="Serena"),
            Voice(voice_id="en_male_glen_emo_v2_mars_bigtts", name="Glen"),
            Voice(voice_id="en_male_sylus_emo_v2_mars_bigtts", name="Sylus"),
            Voice(voice_id="zh_female_cancan_mars_bigtts", name="灿灿/Shiny"),
            Voice(
                voice_id="zh_female_shuangkuaisisi_moon_bigtts",
                name="爽快思思/Skye"),
            Voice(
                voice_id="zh_male_wennuanahu_moon_bigtts",
                name="温暖阿虎/Alvin"),
            Voice(
                voice_id="zh_male_shaonianzixin_moon_bigtts",
                name="少年梓辛/Brayan"),
            Voice(voice_id="zh_male_jingqiangkanye_moon_bigtts",
                  name="京腔侃爷/Harmony"),
            Voice(voice_id="en_female_lauren_moon_bigtts", name="Lauren"),
            Voice(voice_id="en_male_campaign_jamal_moon_bigtts",
                  name="EnergeticMaleII"),
            Voice(voice_id="en_male_chris_moon_bigtts", name="GothamHero"),
            Voice(voice_id="en_female_product_darcie_moon_bigtts",
                  name="FlirtyFemale"),
            Voice(voice_id="en_female_emotional_moon_bigtts",
                  name="PeacefulFemale"),
            Voice(voice_id="en_female_nara_moon_bigtts", name="Nara"),
            Voice(voice_id="en_male_bruce_moon_bigtts", name="Bruce"),
            Voice(voice_id="en_male_michael_moon_bigtts", name="Michael"),
            Voice(voice_id="ICL_en_male_cc_sha_v1_tob", name="CartoonChef"),
            Voice(
                voice_id="zh_male_M100_conversation_wvae_bigtts",
                name="Lucas"),
            Voice(
                voice_id="zh_female_sophie_conversation_wvae_bigtts",
                name="Sophie"),
            Voice(
                voice_id="en_female_dacey_conversation_wvae_bigtts",
                name="Daisy"),
            Voice(
                voice_id="en_male_charlie_conversation_wvae_bigtts",
                name="Owen"),
            Voice(
                voice_id="en_female_sarah_new_conversation_wvae_bigtts",
                name="Luna"),
            Voice(voice_id="ICL_en_male_michael_tob", name="Michael"),
            Voice(voice_id="ICL_en_female_cc_cm_v1_tob", name="Charlie"),
            Voice(voice_id="ICL_en_male_oogie2_tob", name="BigBoogie"),
            Voice(voice_id="ICL_en_male_frosty1_tob", name="FrostyMan"),
            Voice(voice_id="ICL_en_male_grinch2_tob", name="TheGrinch"),
            Voice(voice_id="ICL_en_male_zayne_tob", name="Zayne"),
            Voice(voice_id="ICL_en_male_cc_jigsaw_tob", name="Jigsaw"),
            Voice(voice_id="ICL_en_male_cc_chucky_tob", name="Chucky"),
            Voice(voice_id="ICL_en_male_cc_penny_v1_tob", name="ClownMan"),
            Voice(voice_id="ICL_en_male_kevin2_tob", name="KevinMcCallister"),
            Voice(voice_id="ICL_en_male_xavier1_v1_tob", name="Xavier"),
            Voice(voice_id="ICL_en_male_cc_dracula_v1_tob", name="Noah"),
            Voice(voice_id="en_male_adam_mars_bigtts", name="Adam"),
            Voice(voice_id="en_female_amanda_mars_bigtts", name="Amanda"),
            Voice(voice_id="en_male_jackson_mars_bigtts", name="Jackson"),
            Voice(voice_id="zh_male_jieshuonansheng_mars_bigtts",
                  name="磁性解说男声/Morgan"),
            Voice(
                voice_id="zh_female_jitangmeimei_mars_bigtts",
                name="鸡汤妹妹/Hope"),
            Voice(
                voice_id="zh_female_tiexinnvsheng_mars_bigtts",
                name="贴心女声/Candy"),
            Voice(voice_id="zh_female_mengyatou_mars_bigtts", name="萌丫头/Cutey")
        ],
        "en-GB": [
            Voice(voice_id="zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
                  name="爽快思思（多情感）"),
            Voice(voice_id="en_male_corey_emo_v2_mars_bigtts", name="Corey"),
            Voice(
                voice_id="en_female_nadia_tips_emo_v2_mars_bigtts",
                name="Nadia"),
            Voice(voice_id="zh_female_yingyujiaoyu_mars_bigtts", name="Tina老师"),
            Voice(voice_id="en_female_daisy_moon_bigtts", name="DelicateGirl"),
            Voice(voice_id="en_male_dave_moon_bigtts", name="Dave"),
            Voice(voice_id="en_male_hades_moon_bigtts", name="Hades"),
            Voice(voice_id="en_female_onez_moon_bigtts", name="Onez"),
            Voice(voice_id="en_female_emily_mars_bigtts", name="Emily"),
            Voice(
                voice_id="zh_male_xudong_conversation_wvae_bigtts",
                name="Daniel"),
            Voice(voice_id="ICL_en_male_cc_alastor_tob", name="Alastor"),
            Voice(voice_id="en_male_smith_mars_bigtts", name="Smith"),
            Voice(voice_id="en_female_anna_mars_bigtts", name="Anna")
        ],
        "ja-JP": [
            Voice(
                voice_id="multi_zh_male_youyoujunzi_moon_bigtts",
                name="ひかる（光）"),
            Voice(voice_id="multi_female_sophie_conversation_wvae_bigtts",
                  name="さとみ（智美）"),
            Voice(voice_id="multi_male_xudong_conversation_wvae_bigtts",
                  name="まさお（正男）"),
            Voice(
                voice_id="multi_female_maomao_conversation_wvae_bigtts",
                name="つき（月）"),
            Voice(
                voice_id="multi_female_gaolengyujie_moon_bigtts",
                name="あけみ（朱美）"),
            Voice(voice_id="multi_male_jingqiangkanye_moon_bigtts",
                  name="かずね（和音）/JavierorÁlvaro"),
            Voice(voice_id="multi_female_shuangkuaisisi_moon_bigtts",
                  name="はるこ（晴子）/Esmeralda"),
            Voice(voice_id="multi_male_wanqudashu_moon_bigtts",
                  name="ひろし（広志）/Roberto")
        ],
        "es-MX": [
            Voice(
                voice_id="multi_female_maomao_conversation_wvae_bigtts",
                name="Diana"),
            Voice(
                voice_id="multi_male_M100_conversation_wvae_bigtts",
                name="Lucía"),
            Voice(
                voice_id="multi_female_sophie_conversation_wvae_bigtts",
                name="Sofía"),
            Voice(voice_id="multi_male_xudong_conversation_wvae_bigtts",
                  name="Daníel"),
            Voice(voice_id="multi_male_jingqiangkanye_moon_bigtts",
                  name="かずね（和音）/JavierorÁlvaro"),
            Voice(voice_id="multi_female_shuangkuaisisi_moon_bigtts",
                  name="はるこ（晴子）/Esmeralda"),
            Voice(voice_id="multi_male_wanqudashu_moon_bigtts",
                  name="ひろし（広志）/Roberto")
        ]
    },
    "seed-tts-1.0-concurr": {
        "zh-CN": [
            Voice(voice_id="zh_male_lengkugege_emo_v2_mars_bigtts",
                  name="冷酷哥哥（多情感）"),
            Voice(voice_id="zh_female_tianxinxiaomei_emo_v2_mars_bigtts",
                  name="甜心小美（多情感）"),
            Voice(voice_id="zh_female_gaolengyujie_emo_v2_mars_bigtts",
                  name="高冷御姐（多情感）"),
            Voice(voice_id="zh_male_aojiaobazong_emo_v2_mars_bigtts",
                  name="傲娇霸总（多情感）"),
            Voice(voice_id="zh_male_guangzhoudege_emo_mars_bigtts",
                  name="广州德哥（多情感）"),
            Voice(voice_id="zh_male_jingqiangkanye_emo_mars_bigtts",
                  name="京腔侃爷（多情感）"),
            Voice(voice_id="zh_female_linjuayi_emo_v2_mars_bigtts",
                  name="邻居阿姨（多情感）"),
            Voice(voice_id="zh_male_yourougongzi_emo_v2_mars_bigtts",
                  name="优柔公子（多情感）"),
            Voice(voice_id="zh_male_ruyayichen_emo_v2_mars_bigtts",
                  name="儒雅男友（多情感）"),
            Voice(voice_id="zh_male_junlangnanyou_emo_v2_mars_bigtts",
                  name="俊朗男友（多情感）"),
            Voice(voice_id="zh_male_beijingxiaoye_emo_v2_mars_bigtts",
                  name="北京小爷（多情感）"),
            Voice(voice_id="zh_female_roumeinvyou_emo_v2_mars_bigtts",
                  name="柔美女友（多情感）"),
            Voice(voice_id="zh_male_yangguangqingnian_emo_v2_mars_bigtts",
                  name="阳光青年（多情感）"),
            Voice(voice_id="zh_female_meilinvyou_emo_v2_mars_bigtts",
                  name="魅力女友（多情感）"),
            Voice(voice_id="zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
                  name="爽快思思（多情感）"),
            Voice(voice_id="中文", name="zh_male_shenyeboke_emo_v2_mars_bigtts"),
            Voice(voice_id="zh_female_yingyujiaoyu_mars_bigtts", name="Tina老师"),
            Voice(
                voice_id="ICL_zh_female_wenrounvshen_239eff5e8ffa_tob",
                name="温柔女神"),
            Voice(voice_id="zh_female_vv_mars_bigtts", name="Vivi"),
            Voice(voice_id="zh_female_qinqienvsheng_moon_bigtts", name="亲切女声"),
            Voice(voice_id="ICL_zh_male_shenmi_v1_tob", name="机灵小伙"),
            Voice(voice_id="ICL_zh_female_wuxi_tob", name="元气甜妹"),
            Voice(voice_id="ICL_zh_female_wenyinvsheng_v1_tob", name="知心姐姐"),
            Voice(voice_id="zh_male_qingyiyuxuan_mars_bigtts", name="阳光阿辰"),
            Voice(
                voice_id="zh_male_xudong_conversation_wvae_bigtts",
                name="快乐小东"),
            Voice(voice_id="ICL_zh_male_lengkugege_v1_tob", name="冷酷哥哥"),
            Voice(voice_id="ICL_zh_female_feicui_v1_tob", name="纯澈女生"),
            Voice(voice_id="ICL_zh_female_yuxin_v1_tob", name="初恋女友"),
            Voice(voice_id="ICL_zh_female_xnx_tob", name="贴心闺蜜"),
            Voice(voice_id="ICL_zh_female_yry_tob", name="温柔白月光"),
            Voice(voice_id="ICL_zh_male_BV705_streaming_cs_tob", name="炀炀"),
            Voice(
                voice_id="zh_female_sophie_conversation_wvae_bigtts",
                name="魅力苏菲"),
            Voice(voice_id="ICL_zh_female_yilin_tob", name="贴心妹妹"),
            Voice(voice_id="zh_female_tianmeitaozi_mars_bigtts", name="甜美桃子"),
            Voice(voice_id="zh_female_qingxinnvsheng_mars_bigtts", name="清新女声"),
            Voice(voice_id="zh_female_zhixingnvsheng_mars_bigtts", name="知性女声"),
            Voice(voice_id="zh_male_qingshuangnanda_mars_bigtts", name="清爽男大"),
            Voice(voice_id="zh_female_linjianvhai_moon_bigtts", name="邻家女孩"),
            Voice(voice_id="zh_male_yuanboxiaoshu_moon_bigtts", name="渊博小叔"),
            Voice(voice_id="zh_male_yangguangqingnian_moon_bigtts", name="阳光青年"),
            Voice(voice_id="zh_female_tianmeixiaoyuan_moon_bigtts", name="甜美小源"),
            Voice(voice_id="zh_female_qingchezizi_moon_bigtts", name="清澈梓梓"),
            Voice(voice_id="zh_male_jieshuoxiaoming_moon_bigtts", name="解说小明"),
            Voice(voice_id="zh_female_kailangjiejie_moon_bigtts", name="开朗姐姐"),
            Voice(voice_id="zh_male_linjiananhai_moon_bigtts", name="邻家男孩"),
            Voice(voice_id="zh_female_tianmeiyueyue_moon_bigtts", name="甜美悦悦"),
            Voice(voice_id="zh_female_xinlingjitang_moon_bigtts", name="心灵鸡汤"),
            Voice(voice_id="ICL_zh_female_zhixingwenwan_tob", name="知性温婉"),
            Voice(voice_id="ICL_zh_male_nuanxintitie_tob", name="暖心体贴"),
            Voice(voice_id="ICL_zh_male_kailangqingkuai_tob", name="开朗轻快"),
            Voice(voice_id="ICL_zh_male_huoposhuanglang_tob", name="活泼爽朗"),
            Voice(voice_id="ICL_zh_male_shuaizhenxiaohuo_tob", name="率真小伙"),
            Voice(voice_id="zh_male_wenrouxiaoge_mars_bigtts", name="温柔小哥"),
            Voice(voice_id="zh_female_cancan_mars_bigtts", name="灿灿/Shiny"),
            Voice(
                voice_id="zh_female_shuangkuaisisi_moon_bigtts",
                name="爽快思思/Skye"),
            Voice(
                voice_id="zh_male_wennuanahu_moon_bigtts",
                name="温暖阿虎/Alvin"),
            Voice(
                voice_id="zh_male_shaonianzixin_moon_bigtts",
                name="少年梓辛/Brayan"),
            Voice(voice_id="ICL_zh_female_wenrouwenya_tob", name="温柔文雅"),
            Voice(voice_id="仅中文豆包", name="zh_male_hupunan_mars_bigtts"),
            Voice(voice_id="zh_male_lubanqihao_mars_bigtts", name="鲁班七号"),
            Voice(voice_id="zh_female_yangmi_mars_bigtts", name="林潇"),
            Voice(voice_id="zh_female_linzhiling_mars_bigtts", name="玲玲姐姐"),
            Voice(voice_id="zh_female_jiyejizi2_mars_bigtts", name="春日部姐姐"),
            Voice(voice_id="zh_male_tangseng_mars_bigtts", name="唐僧"),
            Voice(voice_id="zh_male_zhuangzhou_mars_bigtts", name="庄周"),
            Voice(voice_id="zh_male_zhubajie_mars_bigtts", name="猪八戒"),
            Voice(voice_id="zh_female_ganmaodianyin_mars_bigtts", name="感冒电音姐姐"),
            Voice(voice_id="zh_female_naying_mars_bigtts", name="直率英子"),
            Voice(voice_id="zh_female_leidian_mars_bigtts", name="女雷神"),
            Voice(voice_id="zh_female_yueyunv_mars_bigtts", name="粤语小溏"),
            Voice(voice_id="zh_male_yuzhouzixuan_moon_bigtts", name="豫州子轩"),
            Voice(voice_id="zh_female_daimengchuanmei_moon_bigtts", name="呆萌川妹"),
            Voice(voice_id="zh_male_guangxiyuanzhou_moon_bigtts", name="广西远舟"),
            Voice(
                voice_id="zh_male_zhoujielun_emo_v2_mars_bigtts",
                name="双节棍小哥"),
            Voice(voice_id="zh_female_wanwanxiaohe_moon_bigtts", name="湾湾小何"),
            Voice(voice_id="zh_female_wanqudashu_moon_bigtts", name="湾区大叔"),
            Voice(voice_id="zh_male_guozhoudege_moon_bigtts", name="广州德哥"),
            Voice(voice_id="zh_male_haoyuxiaoge_moon_bigtts", name="浩宇小哥"),
            Voice(voice_id="zh_male_beijingxiaoye_moon_bigtts", name="北京小爷"),
            Voice(voice_id="zh_male_jingqiangkanye_moon_bigtts",
                  name="京腔侃爷/Harmony"),
            Voice(voice_id="zh_female_meituojieer_moon_bigtts", name="妹坨洁儿"),
            Voice(
                voice_id="ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob",
                name="纯真少女"),
            Voice(
                voice_id="ICL_zh_male_xiaonaigou_edf58cf28b8b_tob",
                name="奶气小生"),
            Voice(
                voice_id="ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob", name="精灵向导"),
            Voice(
                voice_id="ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob",
                name="闷油瓶小哥"),
            Voice(
                voice_id="ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob",
                name="黯刃秦主"),
            Voice(voice_id="ICL_zh_male_badaozongcai_v1_tob", name="霸道总裁"),
            Voice(voice_id="ICL_zh_female_ganli_v1_tob", name="妩媚可人"),
            Voice(voice_id="ICL_zh_female_xiangliangya_v1_tob", name="邪魅御姐"),
            Voice(voice_id="ICL_zh_male_ms_tob", name="嚣张小哥"),
            Voice(voice_id="ICL_zh_male_you_tob", name="油腻大叔"),
            Voice(voice_id="ICL_zh_male_guaogongzi_v1_tob", name="孤傲公子"),
            Voice(voice_id="ICL_zh_male_huzi_v1_tob", name="胡子叔叔"),
            Voice(voice_id="ICL_zh_female_luoqing_v1_tob", name="性感魅惑"),
            Voice(voice_id="ICL_zh_male_bingruogongzi_tob", name="病弱公子"),
            Voice(voice_id="ICL_zh_female_bingjiao3_tob", name="邪魅女王"),
            Voice(voice_id="ICL_zh_male_aomanqingnian_tob", name="傲慢青年"),
            Voice(voice_id="ICL_zh_male_cujingnansheng_tob", name="醋精男生"),
            Voice(voice_id="ICL_zh_male_shuanglangshaonian_tob", name="爽朗少年"),
            Voice(voice_id="ICL_zh_male_sajiaonanyou_tob", name="撒娇男友"),
            Voice(voice_id="ICL_zh_male_wenrounanyou_tob", name="温柔男友"),
            Voice(voice_id="ICL_zh_male_wenshunshaonian_tob", name="温顺少年"),
            Voice(voice_id="ICL_zh_male_naigounanyou_tob", name="粘人男友"),
            Voice(voice_id="ICL_zh_male_sajiaonansheng_tob", name="撒娇男生"),
            Voice(voice_id="ICL_zh_male_huoponanyou_tob", name="活泼男友"),
            Voice(voice_id="ICL_zh_male_tianxinanyou_tob", name="甜系男友"),
            Voice(voice_id="ICL_zh_male_huoliqingnian_tob", name="活力青年"),
            Voice(voice_id="ICL_zh_male_kailangqingnian_tob", name="开朗青年"),
            Voice(voice_id="ICL_zh_male_lengmoxiongzhang_tob", name="冷漠兄长"),
            Voice(voice_id="ICL_zh_male_tiancaitongzhuo_tob", name="天才同桌"),
            Voice(voice_id="ICL_zh_male_pianpiangongzi_tob", name="翩翩公子"),
            Voice(voice_id="ICL_zh_male_mengdongqingnian_tob", name="懵懂青年"),
            Voice(voice_id="ICL_zh_male_lenglianxiongzhang_tob", name="冷脸兄长"),
            Voice(voice_id="ICL_zh_male_bingjiaoshaonian_tob", name="病娇少年"),
            Voice(voice_id="ICL_zh_male_bingjiaonanyou_tob", name="病娇男友"),
            Voice(voice_id="ICL_zh_male_bingruoshaonian_tob", name="病弱少年"),
            Voice(voice_id="ICL_zh_male_yiqishaonian_tob", name="意气少年"),
            Voice(voice_id="ICL_zh_male_ganjingshaonian_tob", name="干净少年"),
            Voice(voice_id="ICL_zh_male_lengmonanyou_tob", name="冷漠男友"),
            Voice(voice_id="ICL_zh_male_jingyingqingnian_tob", name="精英青年"),
            Voice(voice_id="ICL_zh_male_rexueshaonian_tob", name="热血少年"),
            Voice(voice_id="ICL_zh_male_qingshuangshaonian_tob", name="清爽少年"),
            Voice(voice_id="ICL_zh_male_zhongerqingnian_tob", name="中二青年"),
            Voice(voice_id="ICL_zh_male_lingyunqingnian_tob", name="凌云青年"),
            Voice(voice_id="ICL_zh_male_zifuqingnian_tob", name="自负青年"),
            Voice(voice_id="ICL_zh_male_bujiqingnian_tob", name="不羁青年"),
            Voice(voice_id="ICL_zh_male_ruyajunzi_tob", name="儒雅君子"),
            Voice(voice_id="ICL_zh_male_diyinchenyu_tob", name="低音沉郁"),
            Voice(voice_id="ICL_zh_male_lenglianxueba_tob", name="冷脸学霸"),
            Voice(voice_id="ICL_zh_male_ruyazongcai_tob", name="儒雅总裁"),
            Voice(voice_id="ICL_zh_male_shenchenzongcai_tob", name="深沉总裁"),
            Voice(voice_id="ICL_zh_male_xiaohouye_tob", name="小侯爷"),
            Voice(voice_id="ICL_zh_male_gugaogongzi_tob", name="孤高公子"),
            Voice(voice_id="ICL_zh_male_zhangjianjunzi_tob", name="仗剑君子"),
            Voice(voice_id="ICL_zh_male_wenrunxuezhe_tob", name="温润学者"),
            Voice(voice_id="ICL_zh_male_qinqieqingnian_tob", name="亲切青年"),
            Voice(voice_id="ICL_zh_male_wenrouxuezhang_tob", name="温柔学长"),
            Voice(voice_id="ICL_zh_male_gaolengzongcai_tob", name="高冷总裁"),
            Voice(voice_id="ICL_zh_male_lengjungaozhi_tob", name="冷峻高智"),
            Voice(voice_id="ICL_zh_male_chanruoshaoye_tob", name="孱弱少爷"),
            Voice(voice_id="ICL_zh_male_zixinqingnian_tob", name="自信青年"),
            Voice(voice_id="ICL_zh_male_qingseqingnian_tob", name="青涩青年"),
            Voice(voice_id="ICL_zh_male_xuebatongzhuo_tob", name="学霸同桌"),
            Voice(voice_id="ICL_zh_male_lengaozongcai_tob", name="冷傲总裁"),
            Voice(voice_id="ICL_zh_male_yuanqishaonian_tob", name="元气少年"),
            Voice(voice_id="ICL_zh_male_satuoqingnian_tob", name="洒脱青年"),
            Voice(voice_id="ICL_zh_male_zhishuaiqingnian_tob", name="直率青年"),
            Voice(voice_id="ICL_zh_male_siwenqingnian_tob", name="斯文青年"),
            Voice(voice_id="ICL_zh_male_junyigongzi_tob", name="俊逸公子"),
            Voice(voice_id="ICL_zh_male_zhangjianxiake_tob", name="仗剑侠客"),
            Voice(voice_id="ICL_zh_male_jijiaozhineng_tob", name="机甲智能"),
            Voice(voice_id="zh_male_naiqimengwa_mars_bigtts", name="奶气萌娃"),
            Voice(voice_id="zh_female_popo_mars_bigtts", name="婆婆"),
            Voice(voice_id="zh_female_gaolengyujie_moon_bigtts", name="高冷御姐"),
            Voice(voice_id="zh_male_aojiaobazong_moon_bigtts", name="傲娇霸总"),
            Voice(voice_id="zh_female_meilinvyou_moon_bigtts", name="魅力女友"),
            Voice(voice_id="zh_male_shenyeboke_moon_bigtts", name="深夜播客"),
            Voice(voice_id="zh_female_sajiaonvyou_moon_bigtts", name="柔美女友"),
            Voice(voice_id="zh_female_yuanqinvyou_moon_bigtts", name="撒娇学妹"),
            Voice(voice_id="ICL_zh_female_bingruoshaonv_tob", name="病弱少女"),
            Voice(voice_id="ICL_zh_female_huoponvhai_tob", name="活泼女孩"),
            Voice(voice_id="zh_male_dongfanghaoran_moon_bigtts", name="东方浩然"),
            Voice(voice_id="ICL_zh_male_lvchaxiaoge_tob", name="绿茶小哥"),
            Voice(voice_id="ICL_zh_female_jiaoruoluoli_tob", name="娇弱萝莉"),
            Voice(voice_id="ICL_zh_male_lengdanshuli_tob", name="冷淡疏离"),
            Voice(voice_id="ICL_zh_male_hanhoudunshi_tob", name="憨厚敦实"),
            Voice(voice_id="ICL_zh_female_huopodiaoman_tob", name="活泼刁蛮"),
            Voice(voice_id="ICL_zh_male_guzhibingjiao_tob", name="固执病娇"),
            Voice(voice_id="ICL_zh_male_sajiaonianren_tob", name="撒娇粘人"),
            Voice(voice_id="ICL_zh_female_aomanjiaosheng_tob", name="傲慢娇声"),
            Voice(voice_id="ICL_zh_male_xiaosasuixing_tob", name="潇洒随性"),
            Voice(voice_id="ICL_zh_male_guiyishenmi_tob", name="诡异神秘"),
            Voice(voice_id="ICL_zh_male_ruyacaijun_tob", name="儒雅才俊"),
            Voice(voice_id="ICL_zh_male_zhengzhiqingnian_tob", name="正直青年"),
            Voice(voice_id="ICL_zh_female_jiaohannvwang_tob", name="娇憨女王"),
            Voice(voice_id="ICL_zh_female_bingjiaomengmei_tob", name="病娇萌妹"),
            Voice(voice_id="ICL_zh_male_qingsenaigou_tob", name="青涩小生"),
            Voice(voice_id="ICL_zh_male_chunzhenxuedi_tob", name="纯真学弟"),
            Voice(voice_id="ICL_zh_male_youroubangzhu_tob", name="优柔帮主"),
            Voice(voice_id="ICL_zh_male_yourougongzi_tob", name="优柔公子"),
            Voice(voice_id="ICL_zh_female_tiaopigongzhu_tob", name="调皮公主"),
            Voice(voice_id="ICL_zh_male_tiexinnanyou_tob", name="贴心男友"),
            Voice(voice_id="ICL_zh_male_shaonianjiangjun_tob", name="少年将军"),
            Voice(voice_id="ICL_zh_male_bingjiaogege_tob", name="病娇哥哥"),
            Voice(voice_id="ICL_zh_male_xuebanantongzhuo_tob", name="学霸男同桌"),
            Voice(voice_id="ICL_zh_male_youmoshushu_tob", name="幽默叔叔"),
            Voice(voice_id="ICL_zh_female_jiaxiaozi_tob", name="假小子"),
            Voice(voice_id="ICL_zh_male_wenrounantongzhuo_tob", name="温柔男同桌"),
            Voice(voice_id="ICL_zh_male_youmodaye_tob", name="幽默大爷"),
            Voice(voice_id="ICL_zh_male_asmryexiu_tob", name="枕边低语"),
            Voice(voice_id="ICL_zh_male_shenmifashi_tob", name="神秘法师"),
            Voice(voice_id="zh_female_jiaochuan_mars_bigtts", name="娇喘女声"),
            Voice(voice_id="zh_male_livelybro_mars_bigtts", name="开朗弟弟"),
            Voice(voice_id="zh_female_flattery_mars_bigtts", name="谄媚女声"),
            Voice(voice_id="ICL_zh_male_lengjunshangsi_tob", name="冷峻上司"),
            Voice(voice_id="ICL_zh_male_xiaoge_v1_tob", name="寡言小哥"),
            Voice(voice_id="ICL_zh_male_renyuwangzi_v1_tob", name="清朗温润"),
            Voice(voice_id="ICL_zh_male_xiaosha_v1_tob", name="潇洒随性"),
            Voice(voice_id="ICL_zh_male_liyisheng_v1_tob", name="清冷矜贵"),
            Voice(voice_id="ICL_zh_male_qinglen_v1_tob", name="沉稳优雅"),
            Voice(voice_id="ICL_zh_male_chongqingzhanzhan_v1_tob", name="清逸苏感"),
            Voice(voice_id="ICL_zh_male_xingjiwangzi_v1_tob", name="温柔内敛"),
            Voice(voice_id="ICL_zh_male_sigeshiye_v1_tob", name="低沉缱绻"),
            Voice(voice_id="ICL_zh_male_lanyingcaohunshi_v1_tob", name="蓝银草魂师"),
            Voice(voice_id="ICL_zh_female_liumengdie_v1_tob", name="清冷高雅"),
            Voice(voice_id="ICL_zh_female_linxueying_v1_tob", name="甜美娇俏"),
            Voice(voice_id="ICL_zh_female_rouguhunshi_v1_tob", name="柔骨魂师"),
            Voice(voice_id="ICL_zh_female_tianmei_v1_tob", name="甜美活泼"),
            Voice(voice_id="ICL_zh_female_chengshu_v1_tob", name="成熟温柔"),
            Voice(voice_id="ICL_zh_female_xnx_v1_tob", name="贴心闺蜜"),
            Voice(voice_id="ICL_zh_female_yry_v1_tob", name="温柔白月光"),
            Voice(voice_id="zh_male_bv139_audiobook_ummv3_bigtts", name="高冷沉稳"),
            Voice(voice_id="ICL_zh_male_cujingnanyou_tob", name="醋精男友"),
            Voice(voice_id="ICL_zh_male_fengfashaonian_tob", name="风发少年"),
            Voice(voice_id="ICL_zh_male_cixingnansang_tob", name="磁性男嗓"),
            Voice(voice_id="ICL_zh_male_chengshuzongcai_tob", name="成熟总裁"),
            Voice(voice_id="ICL_zh_male_aojiaojingying_tob", name="傲娇精英"),
            Voice(voice_id="ICL_zh_male_aojiaogongzi_tob", name="傲娇公子"),
            Voice(voice_id="ICL_zh_male_badaoshaoye_tob", name="霸道少爷"),
            Voice(voice_id="ICL_zh_male_fuheigongzi_tob", name="腹黑公子"),
            Voice(voice_id="ICL_zh_female_nuanxinxuejie_tob", name="暖心学姐"),
            Voice(voice_id="ICL_zh_female_keainvsheng_tob", name="可爱女生"),
            Voice(voice_id="ICL_zh_female_chengshujiejie_tob", name="成熟姐姐"),
            Voice(voice_id="ICL_zh_female_bingjiaojiejie_tob", name="病娇姐姐"),
            Voice(voice_id="ICL_zh_female_wumeiyujie_tob", name="妩媚御姐"),
            Voice(voice_id="ICL_zh_female_aojiaonvyou_tob", name="傲娇女友"),
            Voice(voice_id="ICL_zh_female_tiexinnvyou_tob", name="贴心女友"),
            Voice(voice_id="ICL_zh_female_xingganyujie_tob", name="性感御姐"),
            Voice(voice_id="ICL_zh_male_bingjiaodidi_tob", name="病娇弟弟"),
            Voice(voice_id="ICL_zh_male_aomanshaoye_tob", name="傲慢少爷"),
            Voice(voice_id="ICL_zh_male_aiqilingren_tob", name="傲气凌人"),
            Voice(voice_id="ICL_zh_male_bingjiaobailian_tob", name="病娇白莲"),
            Voice(
                voice_id="zh_male_M100_conversation_wvae_bigtts",
                name="Lucas"),
            Voice(
                voice_id="zh_female_sophie_conversation_wvae_bigtts",
                name="Sophie"),
            Voice(
                voice_id="zh_male_xudong_conversation_wvae_bigtts",
                name="Daniel"),
            Voice(
                voice_id="multi_zh_male_youyoujunzi_moon_bigtts",
                name="ひかる（光）"),
            Voice(voice_id="ICL_zh_female_lixingyuanzi_cs_tob", name="理性圆子"),
            Voice(voice_id="ICL_zh_female_qingtiantaotao_cs_tob", name="清甜桃桃"),
            Voice(voice_id="ICL_zh_female_qingxixiaoxue_cs_tob", name="清晰小雪"),
            Voice(voice_id="ICL_zh_female_qingtianmeimei_cs_tob", name="清甜莓莓"),
            Voice(voice_id="ICL_zh_female_kailangtingting_cs_tob", name="开朗婷婷"),
            Voice(voice_id="ICL_zh_male_qingxinmumu_cs_tob", name="清新沐沐"),
            Voice(voice_id="ICL_zh_male_shuanglangxiaoyang_cs_tob", name="爽朗小阳"),
            Voice(voice_id="ICL_zh_male_qingxinbobo_cs_tob", name="清新波波"),
            Voice(voice_id="ICL_zh_female_wenwanshanshan_cs_tob", name="温婉珊珊"),
            Voice(voice_id="ICL_zh_female_tianmeixiaoyu_cs_tob", name="甜美小雨"),
            Voice(voice_id="ICL_zh_female_reqingaina_cs_tob", name="热情艾娜"),
            Voice(voice_id="ICL_zh_female_tianmeixiaoju_cs_tob", name="甜美小橘"),
            Voice(voice_id="ICL_zh_male_chenwenmingzai_cs_tob", name="沉稳明仔"),
            Voice(voice_id="ICL_zh_male_qinqiexiaozhuo_cs_tob", name="亲切小卓"),
            Voice(voice_id="ICL_zh_female_lingdongxinxin_cs_tob", name="灵动欣欣"),
            Voice(voice_id="ICL_zh_female_guaiqiaokeer_cs_tob", name="乖巧可儿"),
            Voice(voice_id="ICL_zh_female_nuanxinqianqian_cs_tob", name="暖心茜茜"),
            Voice(voice_id="ICL_zh_female_ruanmengtuanzi_cs_tob", name="软萌团子"),
            Voice(voice_id="ICL_zh_male_yangguangyangyang_cs_tob", name="阳光洋洋"),
            Voice(voice_id="ICL_zh_female_ruanmengtangtang_cs_tob", name="软萌糖糖"),
            Voice(voice_id="ICL_zh_female_xiuliqianqian_cs_tob", name="秀丽倩倩"),
            Voice(voice_id="ICL_zh_female_kaixinxiaohong_cs_tob", name="开心小鸿"),
            Voice(voice_id="ICL_zh_female_qingyingduoduo_cs_tob", name="轻盈朵朵"),
            Voice(voice_id="zh_female_kefunvsheng_mars_bigtts", name="暖阳女声"),
            Voice(voice_id="zh_male_M100_conversation_wvae_bigtts", name="悠悠君子"),
            Voice(
                voice_id="zh_female_maomao_conversation_wvae_bigtts",
                name="文静毛毛"),
            Voice(voice_id="ICL_zh_female_qiuling_v1_tob", name="倾心少女"),
            Voice(voice_id="ICL_zh_male_buyan_v1_tob", name="醇厚低音"),
            Voice(voice_id="ICL_zh_male_BV144_paoxiaoge_v1_tob", name="咆哮小哥"),
            Voice(voice_id="ICL_zh_female_heainainai_tob", name="和蔼奶奶"),
            Voice(voice_id="ICL_zh_female_linjuayi_tob", name="邻居阿姨"),
            Voice(voice_id="zh_female_wenrouxiaoya_moon_bigtts", name="温柔小雅"),
            Voice(voice_id="zh_male_tiancaitongsheng_mars_bigtts", name="天才童声"),
            Voice(voice_id="zh_male_sunwukong_mars_bigtts", name="猴哥"),
            Voice(voice_id="zh_male_xionger_mars_bigtts", name="熊二"),
            Voice(voice_id="zh_female_peiqi_mars_bigtts", name="佩奇猪"),
            Voice(voice_id="zh_female_wuzetian_mars_bigtts", name="武则天"),
            Voice(voice_id="zh_female_gujie_mars_bigtts", name="顾姐"),
            Voice(voice_id="zh_female_yingtaowanzi_mars_bigtts", name="樱桃丸子"),
            Voice(voice_id="zh_male_chunhui_mars_bigtts", name="广告解说"),
            Voice(voice_id="zh_female_shaoergushi_mars_bigtts", name="少儿故事"),
            Voice(voice_id="zh_male_silang_mars_bigtts", name="四郎"),
            Voice(voice_id="zh_female_qiaopinvsheng_mars_bigtts", name="俏皮女声"),
            Voice(voice_id="zh_male_lanxiaoyang_mars_bigtts", name="懒音绵宝"),
            Voice(voice_id="zh_male_dongmanhaimian_mars_bigtts", name="亮嗓萌仔"),
            Voice(voice_id="zh_male_jieshuonansheng_mars_bigtts",
                  name="磁性解说男声/Morgan"),
            Voice(
                voice_id="zh_female_jitangmeimei_mars_bigtts",
                name="鸡汤妹妹/Hope"),
            Voice(
                voice_id="zh_female_tiexinnvsheng_mars_bigtts",
                name="贴心女声/Candy"),
            Voice(
                voice_id="zh_female_mengyatou_mars_bigtts",
                name="萌丫头/Cutey"),
            Voice(
                voice_id="ICL_zh_male_neiliancaijun_e991be511569_tob",
                name="内敛才俊"),
            Voice(voice_id="ICL_zh_male_yangyang_v1_tob", name="温暖少年"),
            Voice(voice_id="ICL_zh_male_flc_v1_tob", name="儒雅公子"),
            Voice(voice_id="zh_male_changtianyi_mars_bigtts", name="悬疑解说"),
            Voice(voice_id="zh_male_ruyaqingnian_mars_bigtts", name="儒雅青年"),
            Voice(voice_id="zh_male_baqiqingshu_mars_bigtts", name="霸气青叔"),
            Voice(voice_id="zh_male_qingcang_mars_bigtts", name="擎苍"),
            Voice(voice_id="zh_male_yangguangqingnian_mars_bigtts", name="活力小哥"),
            Voice(voice_id="zh_female_gufengshaoyu_mars_bigtts", name="古风少御"),
            Voice(voice_id="zh_female_wenroushunv_mars_bigtts", name="温柔淑女"),
            Voice(voice_id="zh_male_fanjuanqingnian_mars_bigtts", name="反卷青年")
        ],
        "en-US": [
            Voice(
                voice_id="en_female_candice_emo_v2_mars_bigtts",
                name="Candice"),
            Voice(voice_id="en_female_skye_emo_v2_mars_bigtts", name="Serena"),
            Voice(voice_id="en_male_glen_emo_v2_mars_bigtts", name="Glen"),
            Voice(voice_id="en_male_sylus_emo_v2_mars_bigtts", name="Sylus"),
            Voice(voice_id="zh_female_cancan_mars_bigtts", name="灿灿/Shiny"),
            Voice(
                voice_id="zh_female_shuangkuaisisi_moon_bigtts",
                name="爽快思思/Skye"),
            Voice(
                voice_id="zh_male_wennuanahu_moon_bigtts",
                name="温暖阿虎/Alvin"),
            Voice(
                voice_id="zh_male_shaonianzixin_moon_bigtts",
                name="少年梓辛/Brayan"),
            Voice(voice_id="zh_male_jingqiangkanye_moon_bigtts",
                  name="京腔侃爷/Harmony"),
            Voice(voice_id="en_female_lauren_moon_bigtts", name="Lauren"),
            Voice(voice_id="en_male_campaign_jamal_moon_bigtts",
                  name="EnergeticMaleII"),
            Voice(voice_id="en_male_chris_moon_bigtts", name="GothamHero"),
            Voice(voice_id="en_female_product_darcie_moon_bigtts",
                  name="FlirtyFemale"),
            Voice(voice_id="en_female_emotional_moon_bigtts",
                  name="PeacefulFemale"),
            Voice(voice_id="en_female_nara_moon_bigtts", name="Nara"),
            Voice(voice_id="en_male_bruce_moon_bigtts", name="Bruce"),
            Voice(voice_id="en_male_michael_moon_bigtts", name="Michael"),
            Voice(voice_id="ICL_en_male_cc_sha_v1_tob", name="CartoonChef"),
            Voice(
                voice_id="zh_male_M100_conversation_wvae_bigtts",
                name="Lucas"),
            Voice(
                voice_id="zh_female_sophie_conversation_wvae_bigtts",
                name="Sophie"),
            Voice(
                voice_id="en_female_dacey_conversation_wvae_bigtts",
                name="Daisy"),
            Voice(
                voice_id="en_male_charlie_conversation_wvae_bigtts",
                name="Owen"),
            Voice(
                voice_id="en_female_sarah_new_conversation_wvae_bigtts",
                name="Luna"),
            Voice(voice_id="ICL_en_male_michael_tob", name="Michael"),
            Voice(voice_id="ICL_en_female_cc_cm_v1_tob", name="Charlie"),
            Voice(voice_id="ICL_en_male_oogie2_tob", name="BigBoogie"),
            Voice(voice_id="ICL_en_male_frosty1_tob", name="FrostyMan"),
            Voice(voice_id="ICL_en_male_grinch2_tob", name="TheGrinch"),
            Voice(voice_id="ICL_en_male_zayne_tob", name="Zayne"),
            Voice(voice_id="ICL_en_male_cc_jigsaw_tob", name="Jigsaw"),
            Voice(voice_id="ICL_en_male_cc_chucky_tob", name="Chucky"),
            Voice(voice_id="ICL_en_male_cc_penny_v1_tob", name="ClownMan"),
            Voice(voice_id="ICL_en_male_kevin2_tob", name="KevinMcCallister"),
            Voice(voice_id="ICL_en_male_xavier1_v1_tob", name="Xavier"),
            Voice(voice_id="ICL_en_male_cc_dracula_v1_tob", name="Noah"),
            Voice(voice_id="en_male_adam_mars_bigtts", name="Adam"),
            Voice(voice_id="en_female_amanda_mars_bigtts", name="Amanda"),
            Voice(voice_id="en_male_jackson_mars_bigtts", name="Jackson"),
            Voice(voice_id="zh_male_jieshuonansheng_mars_bigtts",
                  name="磁性解说男声/Morgan"),
            Voice(
                voice_id="zh_female_jitangmeimei_mars_bigtts",
                name="鸡汤妹妹/Hope"),
            Voice(
                voice_id="zh_female_tiexinnvsheng_mars_bigtts",
                name="贴心女声/Candy"),
            Voice(voice_id="zh_female_mengyatou_mars_bigtts", name="萌丫头/Cutey")
        ],
        "en-GB": [
            Voice(voice_id="zh_female_shuangkuaisisi_emo_v2_mars_bigtts",
                  name="爽快思思（多情感）"),
            Voice(voice_id="en_male_corey_emo_v2_mars_bigtts", name="Corey"),
            Voice(
                voice_id="en_female_nadia_tips_emo_v2_mars_bigtts",
                name="Nadia"),
            Voice(voice_id="zh_female_yingyujiaoyu_mars_bigtts", name="Tina老师"),
            Voice(voice_id="en_female_daisy_moon_bigtts", name="DelicateGirl"),
            Voice(voice_id="en_male_dave_moon_bigtts", name="Dave"),
            Voice(voice_id="en_male_hades_moon_bigtts", name="Hades"),
            Voice(voice_id="en_female_onez_moon_bigtts", name="Onez"),
            Voice(voice_id="en_female_emily_mars_bigtts", name="Emily"),
            Voice(
                voice_id="zh_male_xudong_conversation_wvae_bigtts",
                name="Daniel"),
            Voice(voice_id="ICL_en_male_cc_alastor_tob", name="Alastor"),
            Voice(voice_id="en_male_smith_mars_bigtts", name="Smith"),
            Voice(voice_id="en_female_anna_mars_bigtts", name="Anna")
        ],
        "ja-JP": [
            Voice(
                voice_id="multi_zh_male_youyoujunzi_moon_bigtts",
                name="ひかる（光）"),
            Voice(voice_id="multi_female_sophie_conversation_wvae_bigtts",
                  name="さとみ（智美）"),
            Voice(voice_id="multi_male_xudong_conversation_wvae_bigtts",
                  name="まさお（正男）"),
            Voice(
                voice_id="multi_female_maomao_conversation_wvae_bigtts",
                name="つき（月）"),
            Voice(
                voice_id="multi_female_gaolengyujie_moon_bigtts",
                name="あけみ（朱美）"),
            Voice(voice_id="multi_male_jingqiangkanye_moon_bigtts",
                  name="かずね（和音）/JavierorÁlvaro"),
            Voice(voice_id="multi_female_shuangkuaisisi_moon_bigtts",
                  name="はるこ（晴子）/Esmeralda"),
            Voice(voice_id="multi_male_wanqudashu_moon_bigtts",
                  name="ひろし（広志）/Roberto")
        ],
        "es-MX": [
            Voice(
                voice_id="multi_female_maomao_conversation_wvae_bigtts",
                name="Diana"),
            Voice(
                voice_id="multi_male_M100_conversation_wvae_bigtts",
                name="Lucía"),
            Voice(
                voice_id="multi_female_sophie_conversation_wvae_bigtts",
                name="Sofía"),
            Voice(voice_id="multi_male_xudong_conversation_wvae_bigtts",
                  name="Daníel"),
            Voice(voice_id="multi_male_jingqiangkanye_moon_bigtts",
                  name="かずね（和音）/JavierorÁlvaro"),
            Voice(voice_id="multi_female_shuangkuaisisi_moon_bigtts",
                  name="はるこ（晴子）/Esmeralda"),
            Voice(voice_id="multi_male_wanqudashu_moon_bigtts",
                  name="ひろし（広志）/Roberto")
        ]
    }
}
