#!.venv/bin/python3

import asyncio
from logging import Logger
import logging

from custom_components.volcengine_voice_assistant.sdk.asr import Client


async def run(file: str, url: str, app_key: str, access_key: str,  resource_id: str):
    logger: Logger = logging.getLogger("demo")
    async with Client(logger, url, app_key, access_key,  resource_id) as client:
        await client.connect("demo")

        async def sender():
            async for _ in client.send_file(file):
                pass
            await client.disconnect()
        sender_task = asyncio.create_task(sender())

        try:
            async for response in client.recv():
                logger.info(
                    f"Recv payload msg: {response.payload_msg.get("result").get("text")}")
            logger.info(f"Recv completed")
        except Exception as e:
            logger.error(f"Failed to process audio stream: {e}")

            try:
                sender_task.cancel()
                await sender_task
                logger.info("Sender task cancelled successfully")
            except asyncio.CancelledError:
                logger.info("Sender task was already cancelled")
                pass

            raise

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="ASR WebSocket Client")
    parser.add_argument("--file", type=str, required=True,
                        help="Audio file path")
    parser.add_argument(
        "--url", type=str, default="wss://openspeech.bytedance.com/api/v3/sauc/bigmodel_async", help="WebSocket URL")
    parser.add_argument("--app-key", type=str,  help="App Key")
    parser.add_argument("--access-key", type=str,  help="Access Key")
    parser.add_argument("--resource-id", type=str,
                        default="volc.seedasr.sauc.duration", help="Resource Id")
    args = parser.parse_args()

    asyncio.run(run(args.file, args.url, args.app_key,
                args.access_key, args.resource_id))
