#!.venv/bin/python3

import asyncio
import logging
from logging import Logger

from custom_components.volcengine_voice_assistant.sdk.asr import Client


async def run(file: str, language: str, url: str, app_key: str, access_key: str,  resource_id: str):
    logger: Logger = logging.getLogger(__name__)
    async with Client(logger, url, app_key, access_key,  resource_id) as client:
        await client.async_connect(__name__, language)

        async def async_sender():
            try:
                async for _ in client.async_send_file(file):
                    pass
            except Exception as e:
                logger.error(f"Send audio failed: {e}")
                raise
            finally:
                await client.async_disconnect()
        sender_task = asyncio.create_task(async_sender())

        try:
            async for response in client.async_recv():
                logger.info(
                    f"Recv payload msg: {response.payload_msg.get("result").get("text")}")
        except Exception as e:
            logger.error(f"Failed to process audio stream: {e}")

            try:
                sender_task.cancel()
                await sender_task
                logger.info("Sender task cancelled successfully")
            except asyncio.CancelledError:
                logger.info("Sender task was already cancelled")
                pass

            raise

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="ASR WebSocket Client")
    parser.add_argument("--file", type=str, help="Audio file path")
    parser.add_argument("--language", type=str,
                        default="zh-CN", help="Language")
    parser.add_argument(
        "--url", type=str, default="wss://openspeech.bytedance.com/api/v3/sauc/bigmodel_async", help="WebSocket URL")
    parser.add_argument("--app-key", type=str, required=True, help="App Key")
    parser.add_argument("--access-key", type=str,
                        required=True, help="Access Key")
    parser.add_argument("--resource-id", type=str,
                        default="volc.seedasr.sauc.duration", help="Resource Id")
    args = parser.parse_args()

    asyncio.run(run(args.file, args.language, args.url, args.app_key,
                args.access_key, args.resource_id))
