name: Configuration Updates

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update-valid-voices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install Dependencies
        run: |
          python -m pip install autopep8
      - name: Update Configuration
        run: |
          sed -i '/# VALID_VOICES_START/,/# VALID_VOICES_END/d' ./custom_components/volcengine_voice_assistant/config/__init__.py
          echo "# VALID_VOICES_START" >> ./custom_components/volcengine_voice_assistant/config/__init__.py
          ./hack/generate-valid-voices >> ./custom_components/volcengine_voice_assistant/config/__init__.py
          echo "# VALID_VOICES_END" >> ./custom_components/volcengine_voice_assistant/config/__init__.py
      - name: Format Code
        run: |
          python3 -m autopep8 --in-place --recursive ./custom_components/volcengine_voice_assistant/config/__init__.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: "chore: Automated Configuration Update"
          commit-message: "chore: auto-update configuration"
          delete-branch: true
          labels: automated
