name: Release

on:
  push:
    tags: ["v*.*.*"]

env:
  COMPONENT_NAME: volcengine_voice_assistant
  PACKAGE_NAME: volcengine_voice_assistant.zip

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Update Version
        run: sed -i "s/v0.0.0/${{ github.ref_name }}/g" "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}/manifest.json"
      - name: Compress
        run: |
          cd "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}"
          zip "${{ env.PACKAGE_NAME }}" -r ./
      - name: Publish
        uses: softprops/action-gh-release@v3
        with:
          files: "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}/${{ env.PACKAGE_NAME }}"
